### ISSUE TITLE
Don't show help when the command did what I asked successfully

### ISSUE THREAD

**Issue by nguerrera** [dotnet/templating#2015] opened 2019-07-16 23:12 UTC
Here I'm running `dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.2.2::2.2.5` as instructed by a prior attempt to do dotnet new web --framework netcoreapp2.2 with 3.0 SDK.

It succeeded, but showed me a bunch of help, which is also what happens when things fail so I get the impression that it failed. I don't think all this help output is necessary when the operation to install a template succeeds.

![image](https://user-images.githubusercontent.com/75470/61335979-4ac02800-a7e4-11e9-8514-5cf39a566fce.png)

**Comment by ryanbrandenburg** [comment] 2019-07-19 16:40
Sounds like a duplicate of https://github.com/dotnet/templating/issues/1694, but if the new issue means we re-evaluate leaving this in the backlog I'm on-board 😄. I think this is super confusing for even fairly basic templating scenarios.

**Comment by Eilon** [comment] 2020-02-11 21:14
I have a PR to fix this here: https://github.com/dotnet/templating/pull/2268

**Closed** 2020-02-14 00:22 UTC
