### ISSUE TITLE
Investigate CI run failures

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/templating#4618] opened 2022-04-19 18:13 UTC
The CI failures became more frequent. Investigate failing tests and eliminate the reason.

**Comment by GangWang01** [comment] 2022-04-29 04:48
Recent CI failures were mainly caused by the following occasional test failures on different platforms.
>
1. OSX  
- TemplateSearchCacheReaderTests 
    - CanReadSearchMetadata_FromBlob
    - CanReadLegacySearchMetadata_FromBlob  
- NuGetMetadataSearchProviderTests  
    - SearchOnlineCache
    - SearchLocalCache

    These tests often failed together in on OSX in the same pipeline run. It indicated the tests were experiencing network issue when calling Microsoft.TemplateSearch.Common.Providers.NuGetMetadataSearchProvider.AcquireFileFromCloudAsync(String searchMetadataFileLocation, CancellationToken cancellationToken) which sent http request, according to the error message such as
    > “System.AggregateException : Failed to update search cache. (The SSL connection could not be established, see inner exception.)
    ---- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
    -------- System.Security.Authentication.AuthenticationException : The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown”.

    Disconnecting internet network could repro the test failure with same error message.

2. Windows_NT
- DotnetNewLocaleTests
    - SkipsLocalizationOnInstall_WhenLocalizationValidationFails
    - SkipsLocalizationOnInstall_WhenInvalidFormat
- DotnetNewInstallTests
    - CannotInstallTemplateWithoutMandatoryConfig
    - CanShowWarning_WhenHostDataIsIncorrect

    These test all failed because the command output did not contain expected warning/error which was corresponding to the invalid template.json/dotnetcli.host.json/localization file. These test failures appeared separately. It’s hard to repro the issue on local machine unless the invalid files are deleted. I suspect the test assets were somehow not copied completely to the running machine of the pipeline sometimes.
    It has little possibility that the tests failed with the reasons below since other tests didn’t ever fail with them.
    - It didn’t enumerate files with specific pattern(such as *.host.json) successfully.
    - Loading specific file was skipped. 
    - Logger didn’t output the message in time.

**Comment by GangWang01** [comment] 2022-05-05 03:11
#4676 Flush log outputs explicitly didn't resolve the unstable test issue that the command output did not contain expected warning/error, because its corresponding PR check has 1 failed test DotnetNewInstallTests.CanShowWarning_WhenHostDataIsIncorrect with the same error.

**Comment by vlada-shubina** [comment] 2022-05-10 10:33
First bulk of improvements was done in https://github.com/dotnet/templating/pull/4676, let's see if it helps to remediate the failures or at least find more information.

**Comment by GangWang01** [comment] 2022-05-17 07:40
Regarding test failure about missing expected warning/error, through diagnosing the output with debug log, it turned to be a problem existing in logging message by the logger created by LoggerFactory. For example, expected debug log “Found template.json at <the path of being installed template>” didn’t appear in the output, but at the end of the output it told the template was installed successfully.

Thanks to Jan for pointing out how to try reproducing the problem and resolve! In repo https://github.com/GangWang01/TestMSLoggingConsole, commit 66a40e2 can repro missing logged messages easily, and commit f5a8bb7 resolves the problem. 

To fix this issue, it needs to dispose LoggerFactory created in CliTemplateEngineHost as well as calling its Dispose().

**Comment by GangWang01** [comment] 2022-05-31 02:08
Recent CI runs didn't have the flaky issues. It looks like we may close it.

**Closed by GangWang01** 2022-05-31 02:08 UTC
Labels: triaged, need-investigation
