### ISSUE TITLE
Custom template with dynamic code generation

### ISSUE THREAD

**Issue by srsaggam** [dotnet/templating#1728] opened 2018-12-28 08:23 UTC
Is it possible to have a custom template which can take input from user and produce dynamic code based on the user input.
use case scenario:
* user has an input file that he want to pass when he creates project using  'dotnet new customtemplate'
* based in this input file we may want to call other library and generate code based on that call. So the generated code inside the template is not static its dynamic based on the input given and the call to the "other" library.

Is this possible to do with templates? If the answer is yes. Is there any examples demonstrating similar use cases?

**Comment by srsaggam** [comment] 2019-01-02 21:36
Could you also help me find examples on how to create a new post action on a custom template?

Example:
donet new customtemplate 
generates a csproj with program.cs which has console.writeline("foo")

I would like a post action which can modify console.writeline("foo") to console.writeline("bar") in program.cs 

How can I accomplish this?

**Comment by danmosemsft** [comment] 2019-01-02 21:36
@seancpeters is this something you can help us with? We're working with @srsaggam 's team in the AI org to add new templates

**Comment by seancpeters** [comment] 2019-01-02 21:44
@srsaggam @danmosemsft 

Could you provide more detail on the original question regarding a user input file. Would the file contain configuration, or would it be a code file that should be executed? I'm not sure what your "other library" would be like, or how it would be referenced.

**Comment by srsaggam** [comment] 2019-01-02 22:01
@seancpeters 

Here is what my need looks like:

User does some thing like this:

dotnet new mytemplate -datafile "c:\ml.csv" -customargs "blah"

This should create a project(cs.proj) with program.cs

The content of the program.cs may be determined based on the user input file.
This dynamic content may be generated in the postaction script.

for example the program.cs may contain:
file.open("c:\ml.csv")
and some other steps based on the content in that csv. which is determined in the post action script

**Comment by seancpeters** [comment] 2019-01-02 22:04
For the second question - on custom post actions, if your example is an actual use case, that sort of thing can be accomplished with the existing symbol replacement functionality in templating. For example, if you define a symbol in your template.json like this:
```
"symbols": {
  "NewFoolValue": {
    "type": "parameter",
    "datatype": "string",
    "defaultValue": "bar",
    "replaces": "foo",
    "description": "The value of this symbol replaces 'foo' in the generated content"
}
```

**Comment by srsaggam** [comment] 2019-01-02 22:09
I have given that simple example just to give you guys an idea of what functionality I'm looking for. I do not want symbol replacement. I'm basically looking to execute some custom code(which takes in user input provide when using dotnet new … ) in post action script.

**Comment by seancpeters** [comment] 2019-01-02 22:11
`dotnet new mytemplate -datafile "c:\ml.csv" -customargs "blah"`

Would the datafile contain all of the content of program.cs? Or are you planning to ship a program.cs in the template, and have the input file contain some options which cause pieces of your program.cs to conditionally be included / excluded / modified?

The existing template processing functionality includes the ability to conditionally include or exclude content within any file in the template content. For example this file in the "starterweb-csharp" template contains a lot of conditions used by template processing to include / exclude pieces of the file based on the values of user provided parameters.

**Comment by srsaggam** [comment] 2019-01-02 22:20
okay to give more context:

The data file is just the dataset file which the user wants to generate the model out of it.

ideally the program.cs will have:

code generated for train the model, code to do predictions etc

so the content in the program.cs is not static. It will change based on the contents in the dataset file.
So I need a place in post action script which will try to analyze the dataset and give out what kind of training needs to be done on the datafile and based on this I want to generate the content of the program.cs

**Comment by danmosemsft** [comment] 2019-01-02 22:22
cc @eerhardt

**Comment by srsaggam** [comment] 2019-01-02 23:48
I think I'm able to create a post action script and execute it successfully through templates. Now I'm facing another issue.

dotnet new mytemplate -n "myparam1"

inside mytemplate's template.json I have : 
```
"postActions": [
    {
      "actionId": "8cf40c6c-7aaa-4ea9-b018-ad10d946338d",
      "manualInstructions": [
        {
          "text": "post action script"
        }
      ],
      "continueOnError": false,
      "description ": "Says hello"
    }
  ]
```
and my postaction script that I have installed has the following content in process(…)
```
  public bool Process(IEngineEnvironmentSettings settings, IPostAction actionConfig, ICreationResult templateCreationResult, string outputBasePath)
        {
            settings.Host.LogMessage("HELLO welcome to automl. This is a post action script");
            return true;
        }
```

So the question here is How can I access the parameters that were passed through cli 
example:
dotnet new mytemplate -n "param1"

how can I get/pass the value of "param1" to my post action script or is there a way to access it?

**Comment by seancpeters** [comment] 2019-01-02 23:54
It's not possible to access the input parameters in the post actions. 

Also, the content of program.cs would have to be wholly custom generated in your post action. All of the content generation occurs before the post actions run.

One possible approach would be to have your analysis phase run as a stand-alone prior to running dotnet new, having the analysis program output a config file with parameters to pass to dotnet new. There is a little-known parameter to new that allows specifying a file containing parameter key-value pairs that get consumed the same as args on the command line. But this would require running 2 programs:
- The analyzer
- dotnet new (with a reference to the config file generated by the analyzer

**Comment by seancpeters** [comment] 2019-01-02 23:55
Or the analyzer program could invoke dotnet new when it's done.

**Comment by srsaggam** [comment] 2019-01-03 01:46
@seancpeters Thank you for the response 👍 
_"Also, the content of program.cs would have to be wholly custom generated in your post action."_
This may not be the case. We might want to partly replace certain sections of the already generated file.
The reason I asked about accessing the params in post action script because I saw that there is a way to pass arguments to the post actions but dint know how to pass-in the actual command line arguments passed with dotnet new.

```
{
  "author": "AutoML .NET Team.",
  "classifications": [ "ML" ],
  "name": "AutoML Starter",
  "identity": "Microsoft.ML.AutoML", 
  "shortName": "automl", 
  "tags": {
    "language": "C#" 
  },
  "sourceName": "ConsoleApp4", 
  "preferNameDirectory": "true",
  "postActions": [
    {
      "actionId": "8cf40c6c-7aaa-4ea9-b018-ad10d946338d",
      **_"args": {
        "args": "ConsoleApp4"
      },_**
      "manualInstructions": [
        {
          "text": "post action script"
        }
      ],
      "continueOnError": false,
      "description ": "Says hello"
    }
  ]
}
```

And we might not want to do the other approach (2-step) having analyzer run and then create a config file.  :(

**Comment by seancpeters** [comment] 2019-01-03 01:51
The args for post actions are static, they're not interpolated in any way. It could be a reasonable future enhancement to expose the user args to the post actions. I'll need to give that some more thought.

Good point about regular template processing being able to generate an initial version of program.cs

**Comment by srsaggam** [comment] 2019-01-03 01:57
And I assume same will be the case if use existing post-action : [Run Script](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script)
i.e the arguments to the script in there are static too?

**Comment by seancpeters** [comment] 2019-01-03 02:13
That is correct, this limitation is not specific to any post action. 

When invoked, a post action processor is given a limited set of information, as defined here:
https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Cli/PostActionProcessors/IPostActionProcessor.cs

This information does include the primary outputs, which can be examined & used by the post actions if needed - that's how, for example, the restore post action knows which files to run restore on.

**Comment by seancpeters** [comment] 2019-01-03 19:39
I've thought about this some, and may have a workable approach to your situation. Instead of using post actions to do the analysis of the input file, it could be done in a macro, or multiple macros. Macros have the benefit of having access to the input parameters, and they also run prior to content generation. Macros can create symbol name-value pairs, which could be used to control the dynamic generation of the program.cs file (or other files as appropriate).

Here is a good example of a macro (this is a new macro being contributed by a community member, I expect to merge it in the next few days): #1723 
Here is the initial implementation of the "derived" symbol macro. It's not as good an example because the PR has a lot of other refactoring in it, so it's harder to follow: #1194 

The above deal with string manipulations, but you could potentially do a lot more in the macro. The generate port number macro does a fair amount of work to find an available port. This PR #1086 is a modification of the port number macro, it might be of use to look at too.

**Comment by srsaggam** [comment] 2019-01-03 21:18
Based on the PR that you sent for Join Macro I have created the same join macro project locally. I'm unable to create a new template project using that macro . It gives me unable to load newtonsoft version error.

like this: 
```
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
```

I have tried updating the versions on my macro project and dint make a difference.

**Comment by srsaggam** [comment] 2019-01-07 21:36
I have two issues currently:
1) Newtonsoft Json dependency with the latest nuget packs of template engine.
 I got around this by downgrading the nuget packs to a point where it depends on lower vesion of newtonsoft.
2) Not able to substitute general parameters in the macro execution : 
example -
```
"testpath": {
      "dataType": "string",
      "defaultValue": "./test.csv",
      "replaces": "_test_path",
      "type": "parameter"
    },
```
I'm not able to set the value to this from runtime inside the macro. Macro however allows to set the variable which runs it.

**Comment by seancpeters** [comment] 2019-01-07 22:04
For not being able to modify the value of other parameters in a macro execution, this is by design. It's to prevent incorrectly modifying other parameters. One approach you could take is to have the analysis macro set the value of its parameter to a serialized value of your desired config information. Then you could setup derived parameters with value setters that each parse the appropriate piece of the config and set their parameter value.

**Comment by donJoseLuis** [comment] 2020-03-19 20:24
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment] 2020-03-24 17:37
Hello @srsaggam.  This issue has evolved through its' discussion.  The last comment was made over a year ago. Can you please...?
1. Summarize what is the remaining "ask" in this issue?

**Comment by srsaggam** [comment] 2020-03-24 19:19
Hi I don’t remember what was the ask here. We moved away from this to use T4 templates that worked for our use case back then. So you can mark this ask as absolute and close this. Thanks for followup though!

**Closed** 2020-03-24 19:19 UTC
Labels: need-customer-info, triaged

**Comment by irontoby** [comment] 2020-07-16 16:04
I have seen this issue referenced from other locations asking about accessing command-line parameters such as `name` from within `template.json`.

In my case, if the `name` of the project (either supplied using `-n` switch or taken from directory via `preferNameDirectory`) is `MyCorp.FooService`, and the "replaced" name in my template (i.e. the `sourceName`) is `MyCorp.TemplateApp`, I also wanted to transform instances of "just" the last part, so e.g. the string "Hello from TemplateApp API!" should become "Hello from FooService API!".

Here is how I solved that, first by getting the `name` value into a "generated" symbol named `appId`, then stripping off the first part using a regex using a [value form](https://github.com/dotnet/templating/wiki/Runnable-Project-Templates---Value-Forms):

```json
  "symbols": {
    "appId": {
      "type": "derived",
      "valueSource": "name",
      "valueTransform": "serviceNameForm",
      "replaces": "TemplateApp"
    }
  },
  "forms": {
    "serviceNameForm": {
      "identifier": "replace",
      "pattern": "^MyCorp\\.",
      "replacement": ""
    }
  }
```

**Comment by hunainm** [comment] 2021-04-29 16:38
> It's not possible to access the input parameters in the post actions.
> 
> Also, the content of program.cs would have to be wholly custom generated in your post action. All of the content generation occurs before the post actions run.
> 
> One possible approach would be to have your analysis phase run as a stand-alone prior to running dotnet new, having the analysis program output a config file with parameters to pass to dotnet new. There is a little-known parameter to new that allows specifying a file containing parameter key-value pairs that get consumed the same as args on the command line. But this would require running 2 programs:
> 
> * The analyzer
> * dotnet new (with a reference to the config file generated by the analyzer)

Could you please tell me what is the command to take parameters from a file using dotnet new? And whats the format for the file?
