### ISSUE TITLE
.NET Core 2.0 Preview 1 Tooling Breaks Symbols

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#789] opened 2017-05-14 06:27 UTC
Using the `dotnet new` 2.0 Preview 1 tooling causes all code wrapped in symbols to disappear even if they are selected for output. Putting a global.json file in the folder pointing to the 1.0.4 tooling makes it work again. What changes actually made it out to 2.0 Preview 1 if any and are there any breaking changes?

**Comment by mlorbetske** [comment] 2017-05-14 06:51
Most of what went in to preview 2 were feature adds, 1.x/2.0 side by side work (unifying 1.x & 2.0 templates visually) - there should be no breaking changes. Are you seeing this for all file types or just some?

**Comment by RehanSaeed** [comment] 2017-05-14 07:26
It's for the `#region (Kestrel)` symbols used in my template. Give it a try by adding [this](https://github.com/ASP-NET-Core-Boilerplate/Templates/tree/master/Source/Boilerplate.Templates/Content/ApiTemplate) folder and notice that Kestrel is selected by default but is totally removed in the Program.cs file with 2.0 but adding a global.json file pointing to 1.0.4 fixes the issue.

**Comment by mlorbetske** [comment] 2017-05-14 07:56
Thanks for the repro, tracking down the exact cause still. We've been trying to replace our C++ evaluator with something more maintainable & stable for quite a while (it's been running all the same tests to make sure the weren't regressions) & we partially cut over to it (only for configuration condition processing) in 2.0.0 preview 1. Something appears to have slipped through in the way it deals with string comparisons.

**Comment by mlorbetske** [comment] 2017-05-14 09:14
Found the issue:

Kestrel gets defined as a symbol with value true in the first evaluation stage.

Phased evaluation starts (so that computed symbols don't have special ordering considerations) - essentially it starts looping & re-evaluating until things stabilize.

The value "Kestrel" gets treated as "true" in the next pass which creates a comparison "Kestrel" == "true", which evaluates to false.

The bug seems to lie in the portion of the logic that marks things as literals. I'm hoping to get a PR out for this Sunday night or Monday.

**Comment by RehanSaeed** [comment] 2017-05-14 12:53
So does that mean 2.0 is a write-off as far as `dotnet new` is concerned? I'll have to add  a note or something to users explaining how to add a global.json file. Perhaps `dotnet new` templates should be able to target particular versions of tooling to avoid problems like this.

**Comment by mlorbetske** [comment] 2017-05-14 16:40
No, this will be fixed in the next preview and before then in the public nightly builds of the CLI. Templates can target version ranges of the generator (that was introduced in this release as well) via a property in template.json like this   "generatorVersions": "[1.0.0.0-*)" - @seancpeters can speak to the allowed syntax. The version number being checked is the value of the AssemblyFileVersion attribute for the RunnableProjects assembly - this should also be visible when passing --debug:show-config to dotnet new.

**Comment by mlorbetske** [comment] 2017-05-14 17:03
[This line](https://github.com/dotnet/templating/blob/9703a93a90c6cb91e4d265857c54963102c27ef6/src/Microsoft.TemplateEngine.Core/Expressions/Cpp2/Cpp2StyleEvaluatorDefinition.cs#L80) is the cause of the problem. Dereferencing in literals is currently turned on for C++ style expressions. Turning it off & running the test battery, I'll also be verifying with your template - would you mind if we add it to our test battery to help catch regressions like this earlier in the future?

**Comment by RehanSaeed** [comment] 2017-05-15 08:21
`generatorVersions` is a sensible addition. If I specify the older 1.1.1 CLI version will that work? How does it work? Does it just error if you use the wrong dotnet cli version or does it handle using the correct version itself? It should be documented in the [wiki](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) along with current CLI versions.

**Comment by mlorbetske** [comment] 2017-05-15 16:25
It's not the CLI version, it's the version of the runnable project generator assembly. For versions before the one that supports it, specify a max version of 1.0.0 (exclusive). We'll be documenting this on the wiki soon, though it should be captured & documented in the JSON schema already.

**Closed** 2017-05-15 17:49 UTC
Labels: bug
