### ISSUE TITLE
double.Convert fails on PLK locale when used in an expression

### ISSUE THREAD

**Issue by phenning** [dotnet/templating#2073] opened 2019-08-19 21:02 UTC
The following code template code will result in an exception 
```
using System;
#if (TargetFrameworkMajorMinorVersion >= 4.6)
using System.IO;
#endif
```

```
Error while processing file /repro.cs
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToDouble(IFormatProvider provider)
   at System.Convert.ToDouble(Object value)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.Scope.EvaluateSide[T](Object side, Func`2 convert)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.Scope.EvaluateSides[TLeft,TRight,TResult](Object left, Object right, Func`2 convertLeft, Func`2 convertRight, Func`3 combine)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.Scope.Evaluate()
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.Scope.EvaluateSide[T](Object side, Func`2 convert)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.Scope.Evaluate()
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.CppStyleEvaluatorDefinition.EvaluateCondition(IReadOnlyList`1 tokens, IReadOnlyList`1 values)
```

This is due to PLK having a space as the group separator character, and a , as the decimal character. 

Other European locales all specify . as group separator if , is the decimal separator, so we don't see this in other languages.

We should use the invariant culture when converting doubles and floats for use in expressions.

**Comment by donJoseLuis** [comment] 2020-03-20 07:44
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment] 2020-09-22 11:58
@phenning I cannot reproduce this behavior (exception). 
Current behavior: if literal is cannot be parsed (as example 4.6 cannot be parsed in Polish locale) the value of it will be considered as null. Of course, the condition won't work as expected, however no exception occurs. 

I've created https://github.com/dotnet/templating/issues/2542 for discussion, it should solve the issue for locales, however we need to agree on when to implement it.

**Closed** 2020-09-25 16:54 UTC
Labels: size:3.0, triaged
