### ISSUE TITLE
Sort & Remove

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#847] opened 2017-05-23 02:01 UTC
It would be super helpful to clean up both the templates and generated output if a sort was added to the namespace imports as well as removing any duplicate namespaces. This would simplify templates since you could just focus on making sure that your conditions import all of the namespaces you need for that single condition without worrying about what the possible combinations are with your symbols and which ones do and don't need that namespace.

**Comment by mlorbetske** [comment] 2017-05-23 03:29
This is a duplicate of #633

**Closed by mlorbetske** 2017-05-23 03:29 UTC
