### ISSUE TITLE
dotnet new -i, on two private feeds, unauthorized

### ISSUE THREAD

**Issue by maracuja-juice** [dotnet/templating#1545] opened 2018-05-28 12:16 UTC
I have a Template package that I published to a private feed. (let's name it "Nutshell")
I deleted this package from the "Nutshell" NuGet feed and uploaded it to a different private feed, with a newer version. (let's name that one: "Peach", "Nutshell" will get obsolete at some point)
The feeds are both hosted in VSTS.

I created a PAT with the permission of "packaging (read)" and added it to my NuGet config:
```
  <packageSourceCredentials>
    <packageSourceKey>
      <add key="Username" value="myVSTSUserNAme" />
      <add key="ClearTextPassword" value="myToken" />
    </packageSourceKey>
  </packageSourceCredentials>
```

Now when I try to install the package via `dotnet new -i` I always get the error:

```
C:\Program Files\dotnet\sdk\2.1.200\NuGet.targets(114,5): error : Unable to load the service index for source https://nutshell.pkgs.visualstudio.com/_packaging/nutshell/nuget/v3/index.json. [C:\Users\maracujajuice\.templateengine\dotnetcli\v2.1.200\scratch\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.200\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\maracujajuice\.templateengine\dotnetcli\v2.1.200\scratch\restore.csproj]
```

As you can see: It tries to get the package from the "Nutshell" feed (package is deleted in version 1.0) but it should get it from the "Peach" feed where the package is in version 1.2.
If I explicitly state the version (`Template.Package.Name::1.2.0`) it gets the package correctly from the "Peach" feed.
Why does it want to get it from the "Nutshell" feed by default / doesn't try out both as the same package is on both feeds? (once deleted though)
Can you reproduce this problem?

Thanks for your help.

**Comment by maracuja-juice** [comment] 2018-06-06 06:42
@seancpeters Can you reproduce this problem?

**Comment by mlorbetske** [comment] 2018-06-12 00:10
@maracuja-juice behind the scenes, we're just doing a NuGet restore on a csproj and aren't involved in the mechanics of the actual restore itself. From the error message, it doesn't look like it couldn't find the package, but that it couldn't read from that feed at all (from the `Unable to load the service index for source ...` message), given that it returned an unauthorized, it doesn't seem to have accepted the credentials it was presented with (maybe it's this issue https://github.com/NuGet/Home/issues/4938).

I'd suggest pursuing this on the NuGet/Home repo as they'd know better how to address the issue. 

To verify, the project file that `dotnet restore` is being called on (given the package name and version you've mentioned) has these contents:

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="Microsoft.NETCore.App" />
    <PackageReference Include="Template.Package.Name" Version="1.2.0" />
  </ItemGroup>
</Project>
```

You should be able to save this to a csproj locally & call `dotnet restore` on it - which should more directly reproduce this.

**Comment by mlorbetske** [comment] 2018-06-14 16:53
This issue was moved to NuGet/Home#7027

**Comment by mlorbetske** [comment] 2018-06-14 16:54
Moving this to the NuGet team as they'd be able to help best

**Closed by mlorbetske** 2018-06-14 16:53 UTC
Labels: NuGet Related

**Comment by ropstah** [comment] 2018-06-26 22:29
I'm actually running into a similar issue and arrived here via https://github.com/dotnet/cli/issues/7760 -> 
https://github.com/dotnet/templating/issues/1266 -> https://github.com/dotnet/templating/issues/1306.

My scenario is different though in which I'm trying to build a `.NET Core` application using `TeamCity` and the app references a library hosted on a private NuGet server (basic auth).

 **In my case it boils down to the fact that**: `dotnet add package` doesn't take into account the sources and authentication details specified in the `%APPDATA%\Nuget\NuGet.config` file for the current user (nor any of the other `dotnet` commands that interact with NuGet). Perhaps this also goes for `NuGet.config` files for the current solution but this is a no-go for my scenario because those details shouldn't be coupled to the solution source code.
