### ISSUE TITLE
Coundn't Uninstall Piranha.blog version 6...

### ISSUE THREAD

**Issue by esayastem1** [dotnet/templating#2488] opened 2020-09-02 09:11 UTC
I have  been adding piranha CMS using "dotnet new -i Piranha.Templates"  command, when I list using  "dotnet new "piranha cms" --list " there was no piranha.blog or missed from the list and it has given an options to install version 6... and I have done it. but can't uninstall Version 6 ... Piranha.blog or update to version 8...

brings error: 

C:\Users\xxx\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(131,5): error : rzc
generate exited with code -2147450730. [C:\Users\xxx\Documents\Code\PracticalApps\NorthwindCms\NorthwindCms.csproj]

**Comment by esayastem1** [comment] 2020-09-03 09:09
version 6 removed using dotnet new -u Piranha.Blog.CSharp", but how I can create blog then "dotnet new Piranha.BLog" not get the block and makes error

**Comment by esayastem1** [comment] 2020-09-03 09:09
version 6 removed using dotnet new -u Piranha.Blog.CSharp", but how I can create blog then "dotnet new Piranha.BLog" not get the block and makes error

**Comment by esayastem1** [comment] 2020-09-03 09:09
version 6 removed using dotnet new -u Piranha.Blog.CSharp", but how I can create blog then "dotnet new Piranha.BLog" not get the block and makes error

**Comment by donJoseLuis** [comment] 2020-09-07 08:21
@vlada-shubina please take a look. Is this something we have availability for this week or should we include it in our road map & backlog?

**Comment by vlada-shubina** [comment] 2020-09-07 13:19
@esayastem1 
could you please clarify if I understand the sequence of actions correctly:
1. install Piranha CMS templates using `dotnet new -i Piranha.Templates`.   This should have installed the following templates:
```
Templates                                          Short Name          Language      Tags
--------------------------------------------------------------------------------------------------
ASP.NET Core Empty with Piranha CMS                piranha.empty       [C#]          Web/CMS
ASP.NET Core MVC Web with Piranha CMS              piranha.mvc         [C#]          Web/CMS
ASP.NET Core Razor Pages Web with Piranha CMS      piranha.razor       [C#]          Web/CMS
ASP.NET Core Razor pages Piranha CMS Module        piranha.module      [C#]          Web/CMS/Razor
```

2. Indeed piranha.blog is missing as it is not part of the latest package.  So if you run `dotnet new piranha.blog` you'll get the following output
```
dotnet new piranha.blog
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "ASP.NET Core Blog with Piranha CMS" (piranha.blog) from author "Håkan Edling" in pack Piranha.Blog.CSharp
    To use this template, run the following command and try again:
        dotnet new -i Piranha.Blog.CSharp::6.0.1
```
since the latest version piranha.blog was available at is Piranha.Blog.CSharp::6.0.1

3. install `dotnet new -i Piranha.Blog.CSharp::6.0.1` to install this version and then you should be able to see the piranha.blog in the list and create template out of it by using `dotnet new piranha.blog` 
```
dotnet new piranha cms --list
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.


Templates                                          Short Name          Language      Tags
--------------------------------------------------------------------------------------------------
ASP.NET Core Empty with Piranha CMS                piranha.empty       [C#]          Web/CMS
ASP.NET Core MVC Web with Piranha CMS              piranha.mvc         [C#]          Web/CMS
ASP.NET Core Razor Pages Web with Piranha CMS      piranha.razor       [C#]          Web/CMS
ASP.NET Core Razor pages Piranha CMS Module        piranha.module      [C#]          Web/CMS/Razor
ASP.NET Core Blog with Piranha CMS                 piranha.blog        [C#]          Web/MVC/CMS

dotnet new piranha.blog
The template "ASP.NET Core Blog with Piranha CMS" was created successfully.
```

So I couldn't reproduce the error you reported above. 

Could you please confirm if order of your actions is as I explained above? If not, please clarify which commands you run.
Also please provide dotnet version in use (dotnet --version). Thank you.

**Comment by vlada-shubina** [comment] 2020-09-23 12:55
I'm closing the issue due to no timely feedback, please feel free to reopen if the information given is not sufficient or the issue is not reproduced.

**Closed by vlada-shubina** 2020-09-23 12:55 UTC
Labels: need-customer-info, triaged
