### ISSUE TITLE
Adding package references via post action doesn't work

### ISSUE THREAD

**Issue by das-kaesebrot** [dotnet/templating#4991] opened 2022-07-19 19:08 UTC
I'm trying to dynamically add a new package reference to a solution template based on a symbol set previously through parameters in the post actions of my template, like this (package references changed for privacy):
```json
{
   ...
    "symbols": {
        "hosting": {
            "type": "parameter",
            "datatype": "choice",
            "description": "Choose between HttpSys and Kestrel for ASP.NET Core hosting",
            "choices": [
                {
                    "choice": "httpsys",
                    "description": "HttpSys hosting"
                },
                {
                    "choice": "kestrel",
                    "description": "Kestrel hosting"
                }
            ],
            "defaultValue": "httpsys"
        }
        // other params go here...
    },
    "postActions": [
        {
            "condition": "(hosting == 'httpsys')",
            "description": "Adding reference to HttpSys",
            "manualInstructions": [
                { "text": "Manually add the reference to your project file" }
            ],
            "actionId": "B17581D1-C5C9-4489-8F0A-004BE667B814",
            "continueOnError": true,
            "args": {
                "referenceType": "package",
                "reference": "Microsoft.AspNetCore.Server.HttpSys",
                "version": "2.2.6",
                "targetFiles": "MyProject/MyProject.csproj"
            }
        },
        {
            "condition": "(hosting == 'kestrel')",
            "description": "Adding reference to Kestrel",
            "manualInstructions": [
                { "text": "Manually add the reference to your project file" }
            ],
            "actionId": "B17581D1-C5C9-4489-8F0A-004BE667B814",
            "continueOnError": true,
            "args": {
                "referenceType": "package",
                "reference": "Microsoft.AspNetCore.Server.Kestrel",
                "version": "2.2.0",
                "targetFiles": "MyProject/MyProject.csproj"
            }
        }
    ]
}

```

For adding post actions, I've been following the docs for post action registries at https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-a-reference-to-a-project-file.

Running `dotnet new mytemplate -n test123` unfortunately results in a very short error message without an explanation as to why it fails:
```
PS C:\Users\user\repos> dotnet new mytemplate -n test123
The template "App template" was created successfully.

Processing post-creation actions...
Post action failed.
Manual instructions: Manually add the reference to your project file
```

I've verified that the package references are compatible by manually running `dotnet add package Microsoft.AspNetCore.Server.HttpSys --version 2.2.6`, which adds a reference to the newly generated .csproj file just fine. My colleagues have tested the template as well, resulting in the same error message. I've already tried working around this using a powershell script, but it would be way easier to use post actions for this purpose.

dotnet --version: 6.0.301
Platform: Windows

**Comment by vlada-shubina** [comment] 2022-07-20 10:59
@das-kaesebrot 
we recently fixed 2 issues related to this post actions
https://github.com/dotnet/templating/pull/4922
https://github.com/dotnet/templating/pull/4948
but unfortunately those fixes will be released on in .NET 7.

Using JSON array may fix the issue `"targetFiles": [ "MyProject/MyProject.csproj" ]`

**Comment by das-kaesebrot** [comment] 2022-07-21 09:24
Thank you for investigating this, I've attached a simplified templating solution containing the template in question as well as the generated nuget package:
[myapptemplate-simplified.tar.gz](https://github.com/dotnet/templating/files/9158082/myapptemplate-simplified.tar.gz)

**Comment by GangWang01** [comment] 2022-08-08 08:50
For the post-action issue adding reference, root cause is the path of `targetFiles` missed the prefix `./` for relative path. It should look like `"targetFiles": [ "./MyTemplateApp/MyTemplateApp.csproj" ]`.

Since #2810 was fixed, source relative path of file change is prefixed with `./` relative to template source root while getting creation effects. Then the template also needs the prefix matching file changes when processing post action. 

However to get the command like `dotnet new mytemplate -n test123` work well needs the fixes that will be released in .NET 7 as mentioned above.

**Comment by GangWang01** [comment] 2022-08-11 03:54
Update more detail on the investigation above. 

For dotnet 6.0.301 and above, it needs `./` prefix with relative path of `targetFiles` to get adding package reference post action work. But the command like `dotnet new mytemplate -n test123` doesn't work becaus of `-n test123`.  It renames project file when instantiating template. While just as the note of https://github.com/dotnet/templating/wiki/Post-Action-Registry#add-a-reference-to-a-project-file the file name change is ignored when using `targetFiles`.

Commit https://github.com/dotnet/templating/commit/b7dc29745861400991ca519f85bfd8a9eee43fd4 in main branch resolved the problem. `targetFiles` can know the file name change when instantiating template.

**Comment by vlada-shubina** [comment] 2022-08-15 07:36
Thanks @GangWang01 

@das-kaesebrot it seems you can get the desired result when using `"targetFiles": [ "./MyTemplateApp/MyTemplateApp.csproj" ].` though with number of limitations in .NET 6. in .NET 7 we have them all fixed.

please let us know if the workaround works for you and if you need more info on this issue, thank you.

**Comment by das-kaesebrot** [comment] 2022-08-15 08:00
First of all, thanks for the feedback. Unfortunately, I'm not having any success with that either:
```Output from command:
StdOut:
(empty)
StdErr:
Could not find project or directory `./test123/test123.csproj`.```

**Comment by GangWang01** [comment] 2022-08-15 08:23
@das-kaesebrot  As mentioned above the command with `-n test123` is not supported for adding reference post action when using `targetFiles` in .NET 6. Please also see the reason mentioned above.

**Comment by das-kaesebrot** [comment] 2022-08-15 08:31
I'm very sorry, but having to leave out the ability to give the project a name partly defeats the purpose of being able to create a project using a template. Unfortunately, replacing all occurrences of the project name afterwards is not really an option for us.

**Comment by vlada-shubina** [comment] 2022-08-15 08:40
We may consider servicing the following for 6.0.4xx:
- https://github.com/dotnet/templating/pull/4869
- https://github.com/dotnet/templating/pull/4922
- https://github.com/dotnet/templating/pull/4948

I'll keep posted on decision made.

**Comment by vlada-shubina** [comment] 2022-08-31 13:47
We got approval for servicing the fixes. Preliminary, they should delivered with Oct update.

**Closed** 2022-09-13 08:03 UTC
Labels: need-customer-info

**Comment by das-kaesebrot** [comment] 2022-09-13 17:53
Thank you!
