### ISSUE TITLE
[RFC] would you please add a default gitignore file when new a project

### ISSUE THREAD

**Issue by livarcocc** [dotnet/templating#1189] opened 2017-08-07 00:19 UTC
_From @netroby on August 4, 2017 3:4_

by run dotnet new we can create a new project.
would you please add a default .gitignore file to the new created project?

```bash
#cat .gitignore 
bin/
obj/
.vscode/

```

_Copied from original issue: dotnet/cli#7368_

**Comment by mlorbetske** [comment] 2017-08-08 15:28
This is a duplicate of #823

**Closed by mlorbetske** 2017-08-08 15:28 UTC
