### ISSUE TITLE
Mark the 3.0 template packages as shipping packages

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/templating#1983] opened 2019-07-02 23:05 UTC
This is needed to ensure that dotnet new search works for the newer console & class lib templates.

**Comment by grinrag** [comment] 2020-03-10 11:12
Looks like this issue is obsolete. Current `dotnet-sdk` version 3.1 is shipped with console & class lib templates. Everything is working. Mark this issue for grooming the next triage session.

**Comment by grinrag** [comment] 2020-03-17 13:25
Also, I am going to double check that dotnet new search works for console & classlib tamplates for the version 3.0.

**Comment by donJoseLuis** [comment] 2020-03-20 07:13
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by grinrag** [comment] 2020-03-23 10:54
@vijayrkn Could you, please, write steps to reproduce? Currently I cannot reproduce the bug. Thanks.

**Comment by vijayrkn** [comment] 2020-03-24 00:06
This issue is to track publishing the older versions of Console/ClassLib packages to NuGet.org. Also to make sure that 5.0+ packages do get published to NuGet.org for the search functionality to work.

**Comment by bozturkMSFT** [comment] 2021-05-12 11:44
3.0 Templates are shipping today. Closing.

**Closed by bozturkMSFT** 2021-05-12 11:44 UTC
Labels: size:3.0, triaged
