### ISSUE TITLE
Microsoft.TemplateEngine.Cli: missing dependencies

### ISSUE THREAD

**Issue by SLEBB** [dotnet/templating#3192] opened 2021-05-21 14:46 UTC
Hi,

It's not possible to install the Microsoft.TemplateEngine.Cli package because of missing dependencies:
- Microsoft.DotNet.Cli.CommandLine
- Microsoft.DotNet.TemplateLocator

I need to use the IPostActionProcessor to implement my own action. Do you know when the next available RC will be push on nuget regsitry ?

Thanks :)
Seb

**Comment by vlada-shubina** [comment] 2021-05-24 11:39
hi @SLEBB 

We don't plan to release `Microsoft.TemplateEngine.Cli` package due to packages mentioned above. Preview was released by mistake. 

Could you please explain us what are you aiming to do:
- are you trying to implement you own host based on `Microsoft.TemplateEngine.Cli` package and want to add new post actions?
- are you authoring template for `dotnet new` and need a custom post action implemented for it?

Thank you.

**Comment by SLEBB** [comment] 2021-05-25 07:14
Hi, 

Thanks for responding quickly ;)
I definitly not creating my own host based on Microsoft.TemplateEngine.Cli package
But i would like to implement a custom "post action" for all my templates "dotnet new" but also through VS 2019 (with both compatibility, dotnet cli & VS 2019)

Thank you

**Comment by vlada-shubina** [comment] 2021-05-25 13:26
@SLEBB 

Thank you for the feedback.

`IPostActionProcessor` interface in `Microsoft.TemplateEngine.Cli` package initially was intended to be an extension point, so the author could implement it, prepare the package installable by `dotnet new` and use it by the GUID in template post actions. However, later on the decision was made not to publish `Microsoft.TemplateEngine.Cli` package as it has unpublished dependencies, so it generally made a step back for this extensibility as well.

We are considering now to bring this interface to `Microsoft.TemplateEngine.Abstractions` to enable this extensibility (likely happen after .NET 6 is released though), however by implementing `IPostActionProcessor` interface you only create the post action runnable in 'dotnet new'. This post action will not run in Visual Studio. If the purpose is only running the script, you don't need to create new post action - `dotnet new` already has [run script](https://github.com/dotnet/templating/wiki/Post-Action-Registry#run-script) post action available.

@phenning, @sayedihashimi - do you have any plans to support custom post actions for Visual Studio?

**Comment by vlada-shubina** [comment] 2021-05-25 13:49
@SLEBB 

Apologies for possible confusion: "run script" post action is not available in VS2019, the script will only be executed if the template is run via `dotnet new`; so your observations are correct.

As far as I know, there is no way to similar in Visual Studio, @phenning - could you please advise on that? Thank you.

**Comment by phenning** [comment] 2021-05-25 14:14
That is correct, Visual Studio and Visual Studio for Mac don't currently implement the "run script" post action. 

At the time we were integrating the template engine into Visual Studio for the SDK template scenarios, no SDK template needed this functionality, so this was not prioritized. Early on, in order to have community template engine templates in Visual Studio, you would need to them via VSIX and install also install a stub .vstemplate to invoke our wizard. I do know that some customers  invoked their own "post actions" by chaining their own IWizard implementation after ours was run and the template was created to effectively do this in Visual Studio.

That said, now that community templates are more accessible within Visual Studio, via just dotnet new --install, without the need for a VSIX installation, we should consider what would be needed to implement this in a secure way.

**Comment by SLEBB** [comment] 2021-05-25 14:38
Thanks for responding quickly ;)

**Comment by vlada-shubina** [comment] 2021-05-31 12:00
For original issue reported:
- `Microsoft.TemplateEngine.Cli` is not shipping assembly, so the issue is not applicable
- additionally the package has been unlisted from nuget.org

Closing the issue now.

For the support of custom post actions for `dotnet new` CLI, please track: https://github.com/dotnet/templating/issues/3225
For the support of 'run script' and/or custom post actions in Visual Studio, please track: https://github.com/dotnet/templating/issues/3226.

**Closed by vlada-shubina** 2021-05-31 12:00 UTC
Labels: area: Visual Studio, area: components
