### ISSUE TITLE
Visual Studio for Mac ignores parameter values provided by the user

### ISSUE THREAD

**Issue by andychiare** [dotnet/templating#5692] opened 2022-11-29 11:29 UTC
When a template is used with Visual Studio 2022 for Mac, the parameter values provided by the user are ignored and the default values are used instead.
The same template works correctly with .NET CLI and Visual Studio 2022 for Windows.

I used Visual Studio 2022 for Mac ver 17.4 (build 2406)

[Here](https://github.com/andychiare/test-template) is a sample template to use for reproduce the issue.

The template defines two parameters:
- `param`, used in an assignment in `Program.cs`
- `value`, used in `appsettings.json`

They are replaced with the respective default values, `MyParameter` and `MyValue`, instead of the values provided by the user

**Comment by vlada-shubina** [comment] 2022-11-29 11:33
@phenning @mrward could you please check it? Thank you.
Please let me know if we should transfer it.

**Comment by mrward** [comment] 2022-11-29 11:42
Not tested this template, but I suspect this is the same problem that was reported on the feedback site:

https://developercommunity.visualstudio.com/t/dotnet-new-template-dropdown-not-selecti/10212771

If this template results in custom text fields in VS Mac's New Project dialog, then the values set are being ignored. Also affects choice parameters, which map to a combo box/drop down in VS Mac.

**Comment by mrward** [comment] 2022-11-29 12:13
Yes, this is the same as the bug associated with the feedback ticket.

![image](https://user-images.githubusercontent.com/372361/204523145-3162b68b-7318-49a0-81b8-4edc2deefa68.png)

There is a fix for this, not merged yet to VS Mac, and the problem is fixed in this build:

![image](https://user-images.githubusercontent.com/372361/204526035-9399270d-0659-4539-9a46-708429e1d8b1.png)

**Comment by andychiare** [comment] 2022-11-29 13:47
At first glance, it looks like the same problem @mrward

**Comment by andychiare** [comment] 2022-11-29 13:51
Thank you for your quick reply! Is there any estimated date when the fixed build will be released?

**Comment by mrward** [comment] 2022-11-29 13:57
It will be in Visual Studio for Mac 17.5 preview 2. I do not have an exact date but I expect it will be available sometime in December.

**Comment by vlada-shubina** [comment] 2022-12-05 08:13
Closing:
- it is already fixed
- not related to the repo

if the issue is still reproduced in the  Visual Studio for Mac 17.5 preview 2, please comment on this option or preferably open VS feedback issue. Thank you.

**Closed by vlada-shubina** 2022-12-05 08:13 UTC
Labels: area: Visual Studio
