### ISSUE TITLE
dotnet new --install  incorrectly installs unlisted versions

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/templating#894] opened 2017-06-05 02:19 UTC
If a nuget for a template is unlisted it is still installed.

I tested  this with the wildcard syntax `dotnet new --install TemplatePackageName::*` and a single unlisted nuget package

**Comment by mlorbetske** [comment] 2017-06-05 03:45
Since installation is accomplished by creating a csproj that references the package (left of the :: goes in the include of the package reference, right goes in the version metadata) and calling dotnet restore on it, I think the appropriate next steps here would be to generate a csproj that references the unlisted package, verify that the behavior reproduces when just calling dotnet restore on it and creating an issue on the dotnet/cli project.

**Comment by sayedihashimi** [comment] 2017-06-05 18:18
@SimonCropp can you clarify the scenario here? You published a nuget package to nuget.org (or some other nuget repo) and marked it as unlisted. When you execute `dotnet new TemplateName` what are you expecting to happen at that time and what's actually happening?

**Comment by SimonCropp** [comment] 2017-06-06 03:51
the expected behavior is that it would not install with a "no found" error. the actual result was that it did install

**Comment by mlorbetske** [comment] 2017-06-06 05:23
@SimonCropp from looking at the package information on NuGet (https://www.nuget.org/packages/NServiceBus.Template.WindowsService) and trying out what would have been generated, my guess is that `dotnet restore` on the following csproj would have restored the 1.0.0 package (even though it was unlisted - but I can't verify as the 1.0.0 package is now deleted). It (properly) does not install the 1.0.1-alpha* packages as those are tagged as prerelease and `*` will not match prerelease packages (unless the wildcard is in the prerelease indicator portion of the version).

_(approximation of the project file that would be generated per the code [here](https://github.com/dotnet/templating/blob/rel/vs2017/3-Preview2/src/Microsoft.TemplateEngine.Cli/Installer.cs#L153-L162))_
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="Microsoft.NETCore.App" />
    <PackageReference Include="NServiceBus.Template.WindowsService" Version="*" />
  </ItemGroup>

</Project>
```

As mentioned, if what I'm describing is correct, you'll want to file this issue on dotnet CLI. The projects in this repo don't download the packages directly, it generates a csproj referencing the specified package and delegates the download to `dotnet restore`. If the package can't be restored in that generated csproj file, installation fails. So, if `dotnet new -i NServiceBus.Template.WindowsService::*` was installing the templates from the unlisted 1.0.0 version, then `dotnet restore` was restoring that package for the above project file.

**Comment by sayedihashimi** [comment] 2017-06-06 18:24
From my perspective this behavior is correct. I can install an unlisted package into a project by specifying the name. Being unlisted means it won't be included in search results (which we don't have a feature for yet in dotnet new) but if the name is provided by the user then it's valid. Failing with an error in that case isn't the right behavior.

**Comment by SimonCropp** [comment] 2017-06-06 20:49
Doesnt that go against the purpose of "unlisting but not deleting". that being that people who have already used a nuget will never be broken. and those people should always be restoring by version, never installing with no explicit version.

**Comment by sayedihashimi** [comment] 2017-06-06 22:46
We should have consistent behavior to

    Install-Package

From in the Package Manager Window in VS. If the behavior is different then I'd like to understand why.

**Comment by mlorbetske** [comment] 2017-07-21 05:18
Since there hasn't been any movement here & we're using the behavior of NuGet as defined by the CLI (by shelling out to do a restore, using the package ID/version specification supplied by the arguments passed at the command line to the install parameter), closing this. If this is going to be pursued, an issue should either be filed on dotnet/cli or nuget/home with a repro project that, when restored, incorrectly installs an unlisted version.

**Closed by mlorbetske** 2017-07-21 05:18 UTC
