### ISSUE TITLE
NRE when trying to create template

### ISSUE THREAD

**Issue by theimowski** [dotnet/templating#1379] opened 2017-12-22 21:23 UTC
I'm working on [SAFE.Template](https://github.com/SAFE-Stack/SAFE-template) and tried to add a choice parameter symbol to choose server for back-end. When trying to use attached template, I get following Null Reference Exception: 

`dotnet new SAFE --help`:

```
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


SAFE-Stack Web App v0.3.0 (F#)
Author: Tomasz Heimowski
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.GetFileChanges(IGlobalRunSpec spec, IDirectory sourceDir, String targetDir)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.GetCreationEffects(IEngineEnvironmentSettings environmentSettings, ITemplate templateData, IParameterSet parameters, IComponentManager componentManager, String targetDirectory)
   at Microsoft.TemplateEngine.Cli.New3Command.CheckIfTemplateHasScriptRunningPostActions(ITemplate template)
   at Microsoft.TemplateEngine.Cli.New3Command.GetTemplateUsageInformation(ITemplateInfo templateInfo, IParameterSet& allParams, IReadOnlyList`1& userParamsWithInvalidValues, IReadOnlyDictionary`2& variantsForCanonicals, HashSet`1& userParamsWithDefaultValues, Boolean& hasPostActionScriptRunner)
   at Microsoft.TemplateEngine.Cli.New3Command.ShowTemplateGroupHelp(IList`1 templateGroup, Boolean showImplicitlyHiddenParams)
   at Microsoft.TemplateEngine.Cli.New3Command.DisplayTemplateHelpForSingularGroup()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterSingularTemplateManipulationFlowAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<EnterTemplateManipulationFlowAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.New3Command.<ExecuteAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

`dotnet --info`:

```
 dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

I might have used some unsupported configuration, but anyway shouldn't get meaningless NRE exceptions upon testing the template.

[SAFE.Template.0.3.0.zip](https://github.com/dotnet/templating/files/1583493/SAFE.Template.0.3.0.zip)

**Comment by mlorbetske** [comment] 2017-12-28 04:27
Thanks for reporting this, I'll go in to how to adjust the template to get it working below, but the main fix here was to show the cause of the installation failure (that source/target cannot be files - they must be directories). These diagnostics can be seen when passing `--trace:authoring` as an additional argument to `dotnet new` or `dotnet new3` (note that these trace flags are in the process of being introduced and may not be complete in the latest released versions of the CLI, however building this repo will have them).

The issue comes from the following section of your `template.json`

```
  "sources": [
    {
      "source": "./src/Server/ProgramSuave.fs",
      "target": "./src/Server/Program.fs",
      "condition": "(Server == \"suave\")"
    },
    {
      "source": "./src/Server/ProgramGiraffe.fs",
      "target": "./src/Server/Program.fs",
      "condition": "(Server == \"giraffe\")"
    }
  ],
```

It looks like you're attempting to rename a file based on a condition, however, `source` and `target` must refer to directories with content to process rather than individual files. The sources section below has the relevant configuration for accomplishing this.

```
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(Server == \"suave\")",
          "exclude": [ "ProgramGiraffe.fs" ],
          "rename": {
            "ProgramSuave.fs": "Program.fs"
          }
        },
        {
          "condition": "(Server == \"giraffe\")",
          "exclude": [ "ProgramSuave.fs" ],
          "rename": {
            "ProgramGiraffe.fs": "Program.fs"
          }
        }
      ],
      "source": "./src/Server",
      "target": "./src/Server",
    }
  ],
```

Note that this only processes the `./src/Server` folder - to have it process everything, you'll need something more like this (note that `source` and `target` have been removed so that the default `./` values are used):

```
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(Server == \"suave\")",
          "exclude": [ "**/ProgramGiraffe.fs" ],
          "rename": {
            "ProgramSuave.fs": "Program.fs"
          }
        },
        {
          "condition": "(Server == \"giraffe\")",
          "exclude": [ "**/ProgramSuave.fs" ],
          "rename": {
            "ProgramGiraffe.fs": "Program.fs"
          }
        }
      ],
      "copyOnly": [ ".fake/**", ".paket/**" ]
    }
  ],
```

As an aside, there's a rather large `bundle.js.map` file in ./src/Client/public that has some runnable project generator style markup at the end of it. There's a couple things there - first, the way that it's written, this file takes a very long time to process (it exposes a behavior where a token is being searched for - looking from the current position to the end of the file - but cannot be found, the not found result is interpreted as "not found at the position I asked for" and the search begins again from the next position). This issue is fixed in the PR that will be linked shortly. Second, the way the directives are structured in the file will not work, the "turn off conditional processing" directive consumes the remainder of the line it's on, so the rest of the content would never be output (incidentally, it's the search for the newline that's making the processing take a long time). Third, there don't seem to be matching processing directives in the matching `.js` file - so it seems like those directives may not belong in there at all. Often times, `.min.js` and `.js.map` files are excluded from the template by the author as any processing on the matching `.js` file would be difficult to account for in the minified/mapping artifact

**Comment by theimowski** [comment] 2017-12-31 13:07
Thanks @mlorbetske for diagnosing the issue.

I ended up with a following workaround:

```

  "sources": [
    {
      "exclude": "**/ProgramGiraffe.fs",
      "rename": {
        "ProgramSuave.fs" : "Program.fs"
      },
      "condition": "(Server == \"suave\")"
    },
    {
      "exclude": "**/ProgramSuave.fs",
      "rename": {
        "ProgramGiraffe.fs" : "Program.fs"
      },
      "condition": "(Server == \"giraffe\")"
    }
  ],
```

which seems to work for me.

I'm wondering however if there's a better way in the template engine to handle similar cases.
Say I have the `Server` symbol of `choice` dataType, currently with 2 choices but potentially with more choices in future.
Now, based on the value of `Server` symbol, I want to use a specific source file, which will be referenced as `Program.fs` in `Server.fsproj`.
Do you have any recommendations on how to approach that?
With current solution, each new choice would require me to add to `exclude`...

The `bundle.js.map` file has been added accidentally to template, it's generated in build process after project is created from template - should not be there

**Closed** 2018-01-04 18:00 UTC
