### ISSUE TITLE
build.sh fails on OSX

### ISSUE THREAD

**Issue by tintoy** [dotnet/templating#382] opened 2017-02-27 06:13 UTC
Hi.

I'm trying to build `dotnet-new3` so I can test out my new "project template" template (file renames were broken in the current public build and I have to rename the nested `template.json` during deployment or `dotnet-new3` gets confused while installing the template).

At present, I can't seem to get it to build, though. Rather than clog up the issue with a wall of text, I've put the full log [here](https://gist.github.com/tintoy/065234d245945033c8003b496f0ac113).

`dotnet --info` gives:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771
```

I cloned the repository (`master` branch), ran `./build.sh`, and here's a snippet of the output. Looks like it might be a target-framework selection issue (`src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj` targets `net45`, so perhaps it doesn't belong in `build.sh`)?

```
Build Edge...
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.TemplateEngine.Abstractions -> /Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Abstractions/bin/Debug/netstandard1.3/Microsoft.TemplateEngine.Abstractions.dll
  Microsoft.TemplateEngine.Utils -> /Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Utils/bin/Debug/netstandard1.3/Microsoft.TemplateEngine.Utils.dll
/var/folders/yv/x0nzk5f901g4fywjhzdy18qr0000gn/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(7,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(8,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(9,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
obj/Debug/netcoreapp1.0/Microsoft.TemplateEngine.Edge.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
/var/folders/yv/x0nzk5f901g4fywjhzdy18qr0000gn/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,71): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
/var/folders/yv/x0nzk5f901g4fywjhzdy18qr0000gn/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,99): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
/var/folders/yv/x0nzk5f901g4fywjhzdy18qr0000gn/T/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,122): error CS0518: Predefined type 'System.String' is not defined or imported [/Users/tintoy/development/github/tintoy/templating/src/Microsoft.TemplateEngine.Edge/Microsoft.TemplateEngine.Edge.csproj]
```

**Comment by mlorbetske** [comment] 2017-02-27 07:54
This is a duplicate of #290

**Comment by tintoy** [comment] 2017-02-27 07:55
Oops, sorry, I missed that one.

**Closed by mlorbetske** 2017-02-27 07:54 UTC

**Comment by mlorbetske** [comment] 2017-02-27 08:47
@tintoy no worries, that issue has been open longer than it rightfully should - just can't quite seem to get the build script right for macOS. I've gotten it to be pretty close (with what I've got on my borrowed mac), but it's still too broken to check in as an "improvement".

**Comment by tintoy** [comment] 2017-02-27 09:27
Just out of curiosity, why do some projects that appear to be libraries target `netcoreapp1.x` instead of `netstandard1.x`?

**Comment by mlorbetske** [comment] 2017-02-27 09:52
Well, I remembered that there was a reason but couldn't remember what it was, so I went digging for it. Looks like, if that reason ever really existed, it no longer does - a PR changing those libraries to target netstandard1.5 should come out soon (but probably not tonight yet). Good catch!

**Comment by tintoy** [comment] 2017-02-27 09:56
I spent a good 20 mins trying to get it to compile ;-)

**Comment by mlorbetske** [comment] 2017-02-27 10:10
Sorry :s I'll try to get some time to take a look at them again this week. Or maybe @sayedihashimi can figure it out - he's got a mac

**Comment by tintoy** [comment] 2017-02-27 10:43
Heh, no worries, I didn't mean to give you stick about it - I can see it's a tricky issue to solve :-)
