### ISSUE TITLE
NET 5 - dotnet new not working on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [dotnet/templating#2677] opened 2020-11-10 17:14 UTC
# NET 5 dotnet new not working on OpenSuse Tumbleweed

# General

Just installed on OpenSuse and try

dotnet new mvc -o MvcMovie

![image](https://user-images.githubusercontent.com/12284806/98707566-f046c580-235e-11eb-943d-887a03fc17c3.png)

**Comment by DavidKarlas** [comment] 2020-12-02 19:34
@LeandroRezendeCoutinho @mglgmz
Hi, I tried reproducing this issue on both Debian and OpenSuse, but couldn't reproduce :(
Can you please run this two commands, first to install [dotnet-symbol](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-symbol) tool:
```
dotnet tool install -g dotnet-symbol
```
Once this tool is installed can you run:
```
sudo ~/.dotnet/tools/dotnet-symbol /usr/share/dotnet/sdk/5.0.100/*.dll
```
What this will do it will download .pdb files next to .dll files, since that folder is protected on my test system I used `sudo`, notice there will be a lot of http:// errors because not all .dlls in that folder have .pdb symbols on server, this will take ~1min, after this step is complete reproduce the problem and post exception message here, this will allow us to see exact line number where this exception happen and provide fix/workaround.

**Comment by vlada-shubina** [comment] 2020-12-14 11:05
Closing this item. Please do not hesitate to reopen if the issue still happens.

**Closed by vlada-shubina** 2020-12-14 11:05 UTC
Labels: need-customer-info
