### ISSUE TITLE
Blazor based templates not adhering  to modifiers

### ISSUE THREAD

**Issue by isaacrlevin** [dotnet/templating#1942] opened 2019-06-21 20:58 UTC
I am updating the Blazor templates for 3.0 and I am running across an issue when I `dotnet new` the new template I created. I created a new options called **hosted** that will toggle whether or not the Blazor Web Assembly project should use an ASP.NET Core backend.  

**dotnetcli.host.json**
```json
      "Hosted": {
        "longName": "hosted"
      }
```

**Symbol**
```json
    "Hosted": {
      "type": "parameter",
      "datatype": "bool",
      "defaultValue": "false",
      "description": "Whether to use ASP.NET Core Hosted Backend."
    }
```

**Modifiers**
```json
           "condition": "(!Hosted)",
          "exclude": [
            "BlazorHosted-CSharp/Server/**",
            "BlazorHosted-CSharp/Shared/**"
          ]
        },
        {
          "condition": "(Hosted)",
          "exclude": [
            "BlazorHosted-CSharp/Client/wwwroot/sample-data/**"
          ]
        }
```

So basically if hosted is false, I should only have one project generated. This is not working, though I assume I may be doing something wrong. I talked with @seancpeters and he mentioned it may be an issue, so I am tracking here.

**Comment by seancpeters** [comment] 2019-06-21 21:06
I'm not dug too deep into this, but the issue appears to be that files that are renamed are not properly handled by source modifiers.

**Comment by danroth27** [comment] 2019-06-25 05:01
@vijayrkn FYI - looks like this is blocking our template updates.

**Comment by isaac2004** [comment] 2019-06-28 20:39
@danroth27 @vijayrkn is there an ETA for when this work can start (or someone wants to show me where to look)?

**Comment by seancpeters** [comment] 2019-06-29 00:04
As a workaround, in the template source, if you rename the directories that are conditionally excluded, in a way that causes them to not be renamed during template processing, things should work as expected. For example, call the directories "Hosted-CSharp.<type>" instead of "BlazorHosted-CSharp.<type>"

**Comment by seancpeters** [comment] 2019-06-29 00:09
@phenning - The fix for this issue will most like begin in one or both of these places, they're probably the most useful places to start looking:
https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Core/Util/Orchestrator.cs
...in the method RunInternal()

https://github.com/dotnet/templating/blob/stabilize/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/SimpleConfigModel.cs
… in the property IRunnableProjectConfig.Sources

**Comment by donJoseLuis** [comment] 2020-03-20 07:11
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by AR-May** [comment] 2020-09-02 09:18
After running some templates to reproduce the issue, it seems to me that excluding is performed before renaming, so the template engine does the exclude modifier with old, non-renamed files. 

Excluding and renaming are both modifiers and it seems reasonable that we have a certain order for modifiers to be performed.  If we change the current behavior and allow either renamed files to be excluded also (exclude -> rename -> exclude), or just change the order of operations (rename -> exclude), this might be a breaking change for template authors.

Fortunately, there is a workaround for the problem, as stated above. After a discussion with @KathleenDollard, we decided not to fix this, so I am closing the issue. However, if I understood the problem wrong or the workaround does not work and you are still blocked, please do not hesitate to reopen this and continue the discussion.

**Closed by AR-May** 2020-09-02 09:18 UTC
Labels: need-pm-discussion, size:3.0, triaged
