### ISSUE TITLE
dotnet new returns exit code 0 when a template is not found locally

### ISSUE THREAD

**Issue by svick** [dotnet/templating#2706] opened 2020-12-15 11:30 UTC
When I execute `dotnet new` with a template name that is not found locally, and there are also no results online, I get an error exit code, as expected:

```
>dotnet new nonsense
Couldn't find an installed template that matches the input, searching online for one that does...
No templates found matching: 'nonsense'.


>echo %errorlevel%
-2147352562
```

But when I use template that is found online, the exit code is 0:

```
>dotnet new template
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Expecto .net core Template" (expecto) from author "Michal Niegrzybowski" in pack Expecto.Template
    To use this template, run the following command and try again:
        dotnet new -i Expecto.Template::13.0.1

Template name "FAKE - Template" (fake) from author "" in pack fake-template
    To use this template, run the following command and try again:
        dotnet new -i fake-template::5.20.3

Template name "Fable.Template.Electron App" (fable-electron) from author "Andrew Olney" in pack Fable.Template.Electron
    To use this template, run the following command and try again:
        dotnet new -i Fable.Template.Electron::1.0.3

Template name "Carter Template" (carter) from author "Jonathan Channon <jonathan.channon@gmail.com>" in pack CarterTemplate
    To use this template, run the following command and try again:
        dotnet new -i CarterTemplate::5.2.0

... many more results here

>echo %errorlevel%
0
```

Since nothing is actually installed, I think the exit code should be non-zero here.

The name `template` is just an example, the actual command where this was a problem was `dotnet new console` on Azure App Service, which seems to use a version of the .Net SDK without the common templates.

This is somewhat similar to https://github.com/dotnet/templating/issues/1640.

<details><summary>My environment information</summary>

```
>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

**Comment by vlada-shubina** [comment] 2020-12-15 13:31
Thanks @svick 

I'm currently working on changing the error handling for template instantiation in scope of https://github.com/dotnet/templating/issues/2558. 

There will be many changes to that part, including the fix for the issue you've reported.  
I will keep the issue open for now and will report back once the fix is merged..

**Comment by vlada-shubina** [comment] 2021-01-15 11:52
Duplicate: https://github.com/dotnet/templating/issues/1971

**Closed** 2021-01-21 10:26 UTC
Labels: size:1.0, triaged

**Comment by vlada-shubina** [comment] 2021-01-21 10:28
The issue is fixed in scope of error handling improvements done in #2713 - now the error exit code will be returned in case template to run cannot be found.
