### ISSUE TITLE
����ȷ��Ҫ��ԭ����Ŀ��

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/templating#2789] opened 2021-01-14 22:03 UTC
I don't know how to describe this issue.

![image](https://user-images.githubusercontent.com/4510984/104654543-3de10500-56f7-11eb-9284-f06f591f8012.png)

```
.NET SDK (反映任何 global.json):
 Version:   5.0.102
 Commit:    71365b4d42

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by vlada-shubina** [comment] 2021-01-28 10:49
The text is output from `dotnet restore` command.

@GF-Huang could you please try to run `dotnet restore` to see if it has the same issue? Thank you.

**Comment by GF-Huang** [comment] 2021-01-28 12:13
![image](https://user-images.githubusercontent.com/4510984/106137128-403a6900-61a5-11eb-8b9b-f84228032308.png)

`dotnet restore` no this issue.

**Comment by vlada-shubina** [comment] 2021-09-08 14:39
@GF-Huang thank you. 

Could you please try running `dotnet new console` on latest .NET 6 preview to see if the issue is still reproduced?
```
dotnet new console -o restoreTest
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\restoreTest\restoreTest.csproj...
  Determining projects to restore...
  Restored C:\restoreTest\restoreTest.csproj (in 71 ms).
Restore succeeded.

```

The text below is coming from the subprocess.
```
  Determining projects to restore...
  Restored C:\restoreTest\restoreTest.csproj (in 71 ms).
```
If it's still corrupted, this means that issue is not fixed.

The scenario above can never happen since .NET 6 since `-i` is not using `restore` subprocess anymore. If the issue still appears in different case of using sub process, for example when `dotnet restore` is run as the post action, we will continue troubleshooting it. Potentially it might need a fix in `dotnet restore` too.

**Comment by vlada-shubina** [comment] 2021-10-04 10:27
The issue is not reproducible on .NET 6, so closing it. Please comment if still the issue for .NET 6.

**Closed by vlada-shubina** 2021-10-04 10:27 UTC
Labels: triaged, need-customer-info
