### ISSUE TITLE
Item Templating Name Generation

### ISSUE THREAD

**Issue by dansiegel** [dotnet/templating#768] opened 2017-05-07 17:31 UTC
Certain item templates like `solution files` or `web.config`'s can simply be created in the directory. Other item templates, for instance a `Class.cs` item however would have two names it needs to be concerned with. First being the name of the Class/File and second the namespace it should use. 

You could currently try a work around where you force the user to specify one name or the other and replace a placeholder value in the template file. However it would be a better user experience if these types of files could automatically recognize the namespace it should have based on the csproj file root namespace and the file output directory. 

As a more complex scenario I may for instance have item templates like the following: 

```
.
+-- Views
|   +-- Template.xaml
|   +-- Template.xaml.cs
+-- ViewModels
|   +-- TemplateViewModel
```

**Comment by mlorbetske** [comment] 2017-05-08 00:49
This is a duplicate of #338. To sum up current state - what you've suggested is correct, name and namespace come in as two separate parameters. #338 has the current proposal for how automatic detection might be implemented and still be overridable if the user chooses to.

**Closed by mlorbetske** 2017-05-08 00:49 UTC
