### ISSUE TITLE
"A <Choose> must contain at least one <When>." (MSB4085)

### ISSUE THREAD

**Issue by cdibbs** [dotnet/templating#627] opened 2017-04-20 19:29 UTC
I get this msbuild error after trying to turn a VS 2015 solution into a template. My template.json is very simple, as in the example, here:

[https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates)

Running `dotnet new -i ./MySolutionDir` works fine. The error happens when I try to load the solution in VS. Running diff on the .csproj files before and after using them in the template, I see that somewhere along the way, certain \<Choose\> tags are emptied (probably fine?), but not removed.

**Comment by sayedihashimi** [comment] 2017-04-21 16:07
@cdibbs can you point us to a sample that reproduces this issue?

**Comment by cdibbs** [comment] 2017-04-21 19:47
@sayedihashimi Yes. I won't have access to the original example until Monday, but I was able to reproduce the issue simply by creating a new C# class library, and adding a Choose to the top, like so:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Choose>
    <When Condition="'StringA'=='$(Configuration)'"></When>
    <Otherwise></Otherwise>
  </Choose>
```

After running `dotnet new -i ./templatedir` and `dotnet new helloworld` in a new directory, that results in a .csproj beginning with:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Choose>
    <Otherwise></Otherwise>
  </Choose>
```

which causes msbuild to throw the mentioned error. Here is the repo:
[https://github.com/cdibbs/dotnet-choosewhen-error](https://github.com/cdibbs/dotnet-choosewhen-error).

**Comment by cdibbs** [comment] 2017-04-21 19:50
Ohh, and this is with dotnet 2.0.0-preview1-005825.

**Comment by mlorbetske** [comment] 2017-04-21 22:54
@seancpeters could you provide the information on how to turn off conditional processing for a block? This should be listed in the configuration for `**/*.*proj`

**Comment by seancpeters** [comment] 2017-04-21 23:16
I just spent a little time testing with your sample template. It demonstrates a bug - since StringA & Configuration are not known symbols in the context of this template, the condition shouldn't be processed. Until we release a fix for this bug, here's a workaround you can use to force those conditions to not be processed during template creation.

You can wrap a section of a file in flags that explicitly tell the template engine to ignore conditionals within that block. For the `<Choose>` section of your proj file it can be marked up like this:
```
<!--/-:cnd:noEmit -->
<Choose>
    <When Condition="'StringA'=='$(Configuration)'"></When>
    <Otherwise></Otherwise>
  </Choose>
<!--/+:cnd:noEmit -->
```
## Detailed Explanation: (TL/DR)

The leading tag `<!--/-:cnd:noEmit -->` begins with `<!--/` which indicates that what immediately follows is a flag that will adjust the behavior of processing (different file types have different formats, similar to how other template markup varies based on file type). The next piece `-:cnd` says to turn off processing of conditionals until told otherwise (or until EOF). The final piece `:noEmit` indicates that this markup should not appear in the output file. Note that all of this is case-sensitive. 

The trailing tag `<!--/+:cnd:noEmit -->` is identical to the leading tag, except that `-:cnd` is replaced with `+:cnd` which indicates that conditional processing should be turned back on for the rest of the file (or until another directive to turn conditionals off is encountered).

If you want to see these directives in the output file (for testing), omit the `:noEmit` part, so the tags look like this: `<!--/-:cnd -->` `<!--/+:cnd -->` 

I made up the following example to demonstrate these flags, in a context similar to your .csproj file. Things to note are:
- The `noEmit` directives do not show up in the output, but they are respected in that their content did not get processed - the conditions are still there. 
- The parts of the file not wrapped in these directives did get their conditions processed - note the lack of the conditions, and of the false's in the output of those sections.
```
...
  <PropertyGroup Condition="(true)">
    BeforeTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    BeforeFalseCond
  </PropertyGroup>
<!--/-:cnd -->
  <Choose>
    <When Condition="'StringA'=='$(Configuration)'"></When>
    <Otherwise></Otherwise>
  </Choose>
  <PropertyGroup Condition="(true)">
    InTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    InFalseCond
  </PropertyGroup>
<!--/+:cnd -->
  <PropertyGroup Condition="(true)">
    AfterTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    AfterFalseCond
  </PropertyGroup>
  
<!--/-:cnd:noEmit -->
  <PropertyGroup Condition="(true)">
    NoEmitAfterTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    NoEmitAfterFalseCond
  </PropertyGroup>
<!--/+:cnd:noEmit -->
...
```
After this file is processed by dotnet new, the output corresponding to this section will be:
```
  <PropertyGroup>
    BeforeTrueCond
  </PropertyGroup>
<!--/-:cnd -->
  <Choose>
    <When Condition="'StringA'=='$(Configuration)'"></When>
    <Otherwise></Otherwise>
  </Choose>
  <PropertyGroup Condition="(true)">
    InTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    InFalseCond
  </PropertyGroup>
<!--/+:cnd -->
  <PropertyGroup>
    AfterTrueCond
  </PropertyGroup>

  <PropertyGroup Condition="(true)">
    NoEmitAfterTrueCond
  </PropertyGroup>
  <PropertyGroup Condition="(false)">
    NoEmitAfterFalseCond
  </PropertyGroup>
```

**Comment by cdibbs** [comment] 2017-04-21 23:33
@seancpeters Awesome. That will get me moving, at least. Thank you for the info!

**Comment by cdibbs** [comment] 2017-04-24 17:58
I can confirm this works for me. I ended up wrapping large swaths of my .csproj files in the  since there are a lot of conditions, and not only on the Choose/Whens. I left alone the sections needed for guid replacements. The end result is that I now have a working solution template with a lot less fuss than other templating options out there. :-)

Thanks, again, for all your help @seancpeters, @mlorbetske and @sayedihashimi.

**Comment by mlorbetske** [comment] 2017-04-25 05:32
Happy to help @cdibbs, thanks for making templates!

**Closed by mlorbetske** 2017-04-25 05:32 UTC
