### ISSUE TITLE
Document how to escape a Condition

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#1438] opened 2018-02-28 16:37 UTC
Back in the .NET Core 1.1 release I was able to do this in my csproj to conditionally add things:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
<!--#if (AuthoringMode)-->
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);Swagger</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".template.config\**\*" />
  </ItemGroup>
  <!--#endif-->

<ItemGroup Label="Package References">
    <PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="'$(Swagger)' == 'true'" />
</ItemGroup>
</Project>
```

The `Condition="'$(Swagger)' == 'true'"` syntax gives compile time errors in .NET Core 2.0. I discovered somewhere that I can use the following syntaxinstead:

```
<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="$(DefineConstants.Contains('Swagger'))" />
```

This syntax compiles but no longer works with `dotnet new`. Is there a solution to this problem? Should I also be using `#if` comment syntax like this:

```
<!--#if (Swagger)-->
<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="$(DefineConstants.Contains('Swagger'))" />
<!--#endif-->
```

**Comment by seancpeters** [comment] 2018-02-28 20:34
@RehanSaeed - I think the problem is that this:
`<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="'$(Swagger)' == 'true'" />`
should actually be this:
`<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="'Swagger' == 'true'" />`
... assuming the Swagger symbol is a template-defined symbol, and not an MSBuild symbol.

If that doesn't work for you, could you provide the specific error you're getting? Also, is this error from trying to build/run the template source, or from trying to build/run an invocation of the template created via dotnet new?

**Comment by seancpeters** [comment] 2018-02-28 23:48
@RehanSaeed - could you also provide the definition of your swagger symbol in the template.json ? Or if you can point me at a public repo containing this template version, I can take a look directly.

**Comment by RehanSaeed** [comment] 2018-03-06 16:17
### Workaround

I've switched to using the comment syntax to work around this problem. This works but has the downside of not adding/removing the package based on the constants I define.

```
<!--#if (Swagger)-->
<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" />
<!--#endif-->
```

### Can't Build Template Project

```
<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="'$(Swagger)' == 'true'" />
```

The `Condition="'$(Swagger)' == 'true'"` syntax does work when creating a project from the template but using it means that the template project no longer builds. The error it gives is:

> error CS0234: The type or namespace name 'Swagger' does not exist in the namespace 'Boilerplate.AspNetCore' (are you missing an assembly reference?)

This suggests that the project reference has not been added.

### The New 'Correct' Condition Syntax

This syntax allows the template project to build but the templating engine no longer works.

```
<PackageReference Include="Boilerplate.AspNetCore.Swagger" Version="3.0.0" Condition="$(DefineConstants.Contains('Swagger'))" />
```

**Comment by mlorbetske** [comment] 2018-03-06 18:43
Ah, I think I see what's going on here. Adding a `Swagger` property with a value of `true` to the AuthoringMode section should get the `Condition="'$(Swagger)' == 'true'"` syntax to work when building from template source and when generating from the template. We'll also take a look at adding support for the `Contains` operator, but that likely won't land until after the `2.1.0` .NET Core release.

```
<Project Sdk="Microsoft.NET.Sdk.Web">
<!--#if (AuthoringMode)-->
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);Swagger</DefineConstants>
    <Swagger>true</Swagger>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".template.config\**\*" />
  </ItemGroup>
  <!--#endif-->
```

**Comment by RehanSaeed** [comment] 2018-03-07 15:35
That seems to work. Looks like something has fundamentally changed in the way csproj defines constants.

**Comment by behzad888** [comment] 2018-11-05 13:21
Can we use [Choose](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2017) element?

**Comment by Chris-ParkIT** [comment] 2019-06-20 10:07
how does one do the opposite, i.e. Condition="$(!DefineConstants.Contains('Swagger'))" throws an error - I am not sure what the parser is for these conditions, is there another format that would work?

**Comment by RehanSaeed** [comment] 2020-01-27 14:47
Another question I have is how to escape a `Condition`, so that it gets output in the final project instead of resolved and then removed. For example, lets say I have this in my `.csproj`:

```xml
<PropertyGroup Label="Signing">
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
</PropertyGroup>
```

How do I get the exact output above to be created in my project? The `Condition` always gets removed and I end up with this:

```xml
<PropertyGroup Label="Signing">
</PropertyGroup>
```

**Comment by donJoseLuis** [comment] 2020-03-19 18:06
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by vlada-shubina** [comment] 2020-09-09 14:00
@RehanSaeed, the solution how to escape the conditions is documented in another [issue](https://github.com/dotnet/templating/issues/1692#issuecomment-432833640 ), please check if it solves the issue.
I will add this information to wiki article, so it is available for anyone interested.

**Comment by giggio** [comment] 2020-09-21 14:24
@RehanSaeed I see PR #2527 but it is not yet merged, why was this issue closed early?

**Comment by vlada-shubina** [comment] 2020-10-19 10:08
Closing item - the [wiki article](https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax) was updated.

**Closed by vlada-shubina** 2020-10-19 10:08 UTC
Labels: size:2.0, triaged
