### ISSUE TITLE
Display template version with dotnet-new --list

### ISSUE THREAD

**Issue by am11** [dotnet/templating#2129] opened 2019-10-04 11:13 UTC
## Steps to reproduce

```sh
dotnet new --install giraffe-template::0.20.0
dotnet new --list | grep 'Tem\|----\|gir'
```

## Expected  behavior
```sh
Templates                          Version                 Short Name               Language          Tags                                 
----------------------------------------------------------------------------------------------------------------------------------
Giraffe Web App                    0.20.0                   giraffe                  F#                Web/Giraffe/ASP.NET  
```

## Actual behavior

```sh
Templates                                         Short Name               Language          Tags                                 
----------------------------------------------------------------------------------------------------------------------------------
Giraffe Web App                                   giraffe                  F#                Web/Giraffe/ASP.NET  
```

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
```

**Comment by donJoseLuis** [comment] 2020-03-20 08:32
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by bozturkMSFT** [comment] 2021-05-12 11:12
Hi @am11,
 Thanks for the issue. By design, templates don't have version numbers. Packages do, which contain one or more templates. Please see #2909 for changes regarding this issue. Changes suggested by that work item aims to improve the experience around template versions.

**Closed by bozturkMSFT** 2021-05-12 11:12 UTC
Labels: triaged

**Comment by am11** [comment] 2021-05-12 13:57
Great! Looking forward to it. 😎
