### ISSUE TITLE
Add Remove Unused Using Statements Post-Action

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#633] opened 2017-04-21 09:55 UTC
Right now, I have to add `#if` pre-processor directives around my using statements to add or remove certain features. In the example below, `System.Linq` could be used by multiple conditional symbols and it's very hard to work that out without generating the template using every combination of symbol values and then trying to build the project. 

```
#if (Versioning)
    using System.Linq;
#endif
#if (CORS)
    using ApiTemplate.Constants;
#endif
    using Boilerplate.AspNetCore;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
#if (Versioning)
    using Microsoft.AspNetCore.Mvc.ApiExplorer;
#endif
    using Microsoft.AspNetCore.Mvc.Infrastructure;
    using Microsoft.AspNetCore.Mvc.Routing;
#if (HttpsEverywhere)
    using Microsoft.AspNetCore.Rewrite;
#endif
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
```

In my experience with my own templating engine, this is the easist way to make mistakes. A good way around this problem is to get rid of these `#if` directives and use a post-action to remove unused using statements.

**Comment by sayedihashimi** [comment] 2017-04-21 16:06
In the asp.net templates we purposefully leave some extra using statements. I don't think this would be something that we would work on, since I don't think we would use it directly. Let's see if @mlorbetske would be interested in taking a PR for this.

**Comment by mlorbetske** [comment] 2017-04-21 22:55
I'm interested, obviously it'd have to be an opt-in behavior. If we get a PR for this that'd be fantastic.

**Comment by dansiegel** [comment] 2017-05-23 03:37
@mlorbetske I think it would be safe as a default if duplicates were automatically removed. That would seem to resolve the issue that @RehanSaeed and I both have with our templates. Only removing unused namespaces should be an opt in feature... and I would say more often than not I'm adding some extra namespaces to make life easier when you start coding.

**Comment by sayedihashimi** [comment] 2017-06-05 20:30
For VS and `dotnet new` we leave extra using statements so that users can use types without needing to add the usage. Since this is by design, this isn't an item that the team at Microsoft will be working on. If there is a community member, or team, that want's to implement this as a Post Action that can be added to templates we will review that.
I'll close this for now. If someone is going to send a PR please leave a comment here and then we can discuss any details needed to get the PR out and review it.

**Closed by sayedihashimi** 2017-06-05 20:30 UTC
Labels: help wanted
