### ISSUE TITLE
dotnet new console creates a csproj with improper line endings making it hard to edit using notepad

### ISSUE THREAD

**Issue by balachir** [dotnet/templating#372] opened 2017-02-25 03:13 UTC
INSTALL STEPS
Dev15 RTW build d15rel.26224.00 (includes CLI 1.0.0-rc4-004883)

REPRO STEPS
1. New command prompt
2. `dotnet new console`

![image](https://cloud.githubusercontent.com/assets/8246794/23327653/a95ce6de-fac4-11e6-9bf3-73edbfaf8bd8.png)

3. `notepad ConsoleApp2.csproj`

ACTUAL
Line endings do not display correctly in notepad. Makes it very hard to make changes to the csproj using notepad. Open and save csproj in VS did not fix it either, it displays fine in VS though.

EXPECTED
Line endings to display correctly in notepad

![image](https://cloud.githubusercontent.com/assets/8246794/23327675/34a6fc84-fac5-11e6-83a0-daa30ff85799.png)

**Comment by mlorbetske** [comment] 2017-02-25 03:47
Duplicate of #350

**Closed by mlorbetske** 2017-02-25 03:47 UTC
