### ISSUE TITLE
How to ensure correct solution file name?

### ISSUE THREAD

**Issue by VacuumBreather** [dotnet/templating#4252] opened 2022-01-11 19:40 UTC
I am having a hard time figuring out what Visual Studio and the template engine are doing to the solution files.

I have two templates.

The first is a solution template with multiple projects and a sourcename let's say SourceName.
This template includes a solution file that should end up as ProjectName.sln.

If however I name it SourceName.sln, then VisualStudio complains that the solution was modified outside the environment and the user needs to click 'reload'.
So I followed some advice I found online and renamed the file to Solution.sln. Visual Studio correctly renames that, using the specified project name, and no more unwanted prompt.
However, how do I rename this solution file if the template is instantiated via CLI?

I found the suggestion of using a conditional 
```
        "condition": "(HostIdentifier == \"dotnetcli\" ||  HostIdentifier == \"dotnetcli-preview\")",
```

However how do I use that?

The following doesn't work

    "sources": [
      {
        "exclude": [
          "**/.vs/**",
          "**/.template.config/**",
          "**/bin/**",
          "**/obj/**"
        ],
        "condition": "(HostIdentifier == \"dotnetcli\" ||  HostIdentifier == \"dotnetcli-preview\")",
        "rename": {
          "Solution.sln": "SourceName.sln"
        }
      }
    ],

The template stops working. Also I'm assuming that this condition would inclue the exclude directive also, which should always be active. I want that condition exclusively on the rename. But with this, an empty project directory is created, so this isn't working.

The second template also has a solution file issue. In this case it is a project template.
I need the generated solution file to have a postfix. The csproj file is called SourceName-postfix.csproj
That gets renamed by Visual Studio to ProjectName-postfix.csproj just fine. However, if I include a SourceName-postfix.sln file
in the template, then VS also renames that one, but also adds a ProjectName.sln which I don't want.
Alternatively I'm declaring the template as a solution template. But now Visual Studio is renaming my existing one to ProjectName.sln instead of adding one. Either way I end up with a solution with the wrong name.
I tried the "rename" directive but it doesn't work. The solution remains wrongly named.

I'm having a really hard time figuring out how to ensure the correct solution naming under all these use cases for both CLI and Visual Studio usage.

Any help would be very appreciated.

**Comment by sayedihashimi** [comment] 2022-01-11 20:00
@phenning should be able to help with this question. When we get it resolved I will update the readme at https://aka.ms/netcore-templates

**Comment by VacuumBreather** [comment] 2022-01-12 11:08
I changed the conditional of the first template to this, which doesn't seem to work either however.

```
    "sources": [
      {
        "exclude": [
          "**/.vs/**",
          "**/.template.config/**",
          "**/bin/**",
          "**/obj/**"
        ],
        "modifiers": [{
          "condition": "(HostIdentifier == \"dotnetcli\" || HostIdentifier == \"dotnetcli-preview\")",
          "rename":  { "Solution.sln": "SourceName.sln" }
        }]
      }
    ],
```

The conditional seems to evaluate to false every time. If I use (True) in the conditional, the renaming works.

**Comment by phenning** [comment] 2022-01-12 13:59
The conditional looks correct.

I think you may be missing the bind for the HostIdentifier in your symbols, so it is resolving as false since HostIdentifier is not bound.

Try adding the following to your symbols in your template.json

```
"symbols": {
    "HostIdentifier": {
      "type": "bind",
      "binding": "HostIdentifier"
    }
}
```

**Comment by VacuumBreather** [comment] 2022-01-12 14:12
Alright this actually solved the first template. (What exactly does this binding do? It looks like binding something to itself. I'm not sure I understand why this is even needed?)

Regarding the other project however, I still have the same issue.
The renaming works just fine.

Solution.sln gets renamed to ProjectName-postfix.sln
However when instantiated via IDE, Visual Studio creates an additional ProjectName.sln and then deleted the ProjectName-postfix.sln, since it apparently doesn't recognize that this is the one I'm trying to use.

How do I need to set this up to end up with a single solution file called ProjectName-postfix.sln?

**Comment by phenning** [comment] 2022-01-12 14:25
Think of the symbol names as parameters you can use in your template, either in the template content or from within the template.json itself.  some different symbol types are "parameter", "computed", "generated" or "bind". "Parameter" types are what you can use to gather information from the user of the template.  In the case of "bind", we are binding to the host provided property called "HostIdentifer" and exposing to the template it using the same name. (alternatively you could do the following:

```
"symbols": {
    "Alexander": {
      "type": "bind",
      "binding": "HostIdentifier"
    }
}


        "modifiers": [{
          "condition": "(Alexander== \"dotnetcli\" || Alexander== \"dotnetcli-preview\")",
          "rename":  { "Solution.sln": "SourceName.sln" }
        }]
```

@vlada-shubina can probably point you to additional documentation about the other symbol types and their usage.

The other behavior you are describing is by design. Visual Studio will always use the VS created solution, since that is what the user provided as the solution name in the New Project Dialog. For solution templates though, if one is supplied, we will merge in any modifications (such as solution folders, etc) which you had made to Visual Studio created project.

Sayed has some good information written up [here ](https://github.com/sayedihashimi/template-sample#how-to-create-a-multi-project-solution-template) in regards to some additional things you may need to do to make sure guids get merged properly.

**Comment by VacuumBreather** [comment] 2022-01-12 14:31
> The other behavior you are describing is by design. Visual Studio will always use the VS created solution, since that is what the user provided as the solution name in the New Project Dialog.

Hm, so there's no way to modify the final solution name to be the name the user entered plus a postfix? That's a little bit of an issue for my usecase. The user cannot add the postfix to the entered name, since that's not what's supposed to be used as the project name. I need the project name the user enters to be something else than what the solution file is called. Is there any way to achieve that?

**Comment by vlada-shubina** [comment] 2022-01-13 13:14
> @vlada-shubina Vlada Shubina FTE can probably point you to additional documentation about the other symbol types and their usage.

Documentation on various symbols types is here: https://github.com/dotnet/templating/wiki/Reference-for-template.json#symbols
Please let me know if you have further questions.

**Comment by phenning** [comment] 2022-01-13 15:11
The Visual Studio created solution name is driven by the value specified in the new project dialog. New project dialog does allow users to specify a different solution name from the project name at the time of creation. However, there is not a concept of a "DefaultSolutionName" as there is for "DefaultName" exists for project.

![Screenshot 2022-01-13 101030](https://user-images.githubusercontent.com/2433750/149356060-d425166c-300b-4eea-b98f-30603f939b8c.png)
.

**Comment by VacuumBreather** [comment] 2022-01-13 15:24
Solution and project need to end up in the same folder so that doesn't help. Is there any way to run code after project creation to rename the solution file or anything like that?

**Comment by vlada-shubina** [comment] 2022-02-07 14:28
Closing the issue. 

Modifying solution name in Visual Studio after solution name is specified in new project dialog is unfortunately not possible.
There is no plan to change this behavior in the near future, also it is not aligned with current design.

**Closed by vlada-shubina** 2022-02-07 14:28 UTC
Labels: area: Visual Studio
