### ISSUE TITLE
Templates create files with the executable bit set

### ISSUE THREAD

**Issue by baronfel** [dotnet/templating#473] opened 2017-03-23 17:30 UTC
![image](https://cloud.githubusercontent.com/assets/573979/24261226/4b409784-0fc4-11e7-8744-55b8eac17eaf.png)

Here I create a solution and two projects, both class libraries, one in c#, one in f#. All source files, project files, and solutions have the executable bit set.  Is this necessary?

**Comment by mlorbetske** [comment] 2017-03-23 18:02
This is a duplicate of #240. This should be fixed in the move to .NET Core 2.0

**Closed by mlorbetske** 2017-03-23 18:02 UTC
