### ISSUE TITLE
Excluding Files Does Not Remove Them From A Solution

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/templating#3028] opened 2021-04-13 08:45 UTC
If I have a solution containing a file `appveyor.yml` as a solution item and I have a symbol that excludes the file. The file is not removed from the solution file. I would expect that to happen for me.

```json
{
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(!AppVeyor)",
          "exclude": [
            "appveyor.yml"
          ]
        }
      ]
    }
  ],
  "symbols": {
    "AppVeyor": {
      "type": "parameter",
      "datatype": "bool",
      "description": "Adds AppVeyor continuous integration build file appveyor.yml.",
      "defaultValue": "false"
    }
  }
}
```

**Comment by DavidKarlas** [comment] 2021-04-13 09:07
My suspicion is this might be caused by .yml not being included in https://github.com/dotnet/templating/issues/282

But `modifers` shouldn't depend on that anyway... Tnx for reporting this!

**Comment by vlada-shubina** [comment] 2021-05-24 16:57
@RehanSaeed 
Template engine does not know how to parse solution file when generating template (as any other file format). It only reads the conditional statements as defined in [standard] (https://github.com/dotnet/templating/wiki/Reference-for-comment-syntax) and custom operation config for specific file formats, and include / exclude content based on calculated statements.

Therefore, it doesn't know if any of excluded files in template.json are part of other file types and cannot exclude them. Exclude operation in this context means only that the source file will not be copied to target directory on template instantiation. 
To exclude solution items based on parameter values, you'll need additionally apply condition on it in sln file itself. 

We are considering  *proj-aware generators, perhaps also sln-aware generators for template engine, which would be able to read, apply specific checks and operations on these formats, but nothing beyond discussions at the moment.

**Comment by bekir-ozturk** [comment] 2021-06-07 09:52
I will close this issue now. @RehanSaeed please reply if we should reopen this.

**Closed by bekir-ozturk** 2021-06-07 09:52 UTC
Labels: need-customer-info, triaged

**Comment by RehanSaeed** [comment] 2021-06-07 10:00
> We are considering *proj-aware generators, perhaps also sln-aware generators for template engine, which would be able to read, apply specific checks and operations on these formats, but nothing beyond discussions at the moment.

This would be really nice.
