### ISSUE TITLE
Different fileRename behavior on CLI and Visual Studio 2019 

### ISSUE THREAD

**Issue by McMlok** [dotnet/templating#3524] opened 2021-07-23 10:53 UTC
Hello,

I created my custom solution template where I need to name folder with name generated by casing generator. I use attribute fileRename to rename folder. When I use dotnet new CLI it works but when I use template inside VisualStudio create new project dialog the folder end with name defined in the template.

I made repro [repository](https://github.com/McMlok/dotnetTemplateTest) to demonstrate how I use attribute. Is attribute fileRename supported when template is used in Visual Studio?

dotnet Core: 5.0.302
Visual Studio 2019: 16.10.4

Thank you

**Comment by vlada-shubina** [comment] 2021-07-23 18:55
@McMlok 
`fileRename` for generated symbols is a fairly new feature - was introduced in 5.0.2xx. Visual Studio 16.10.4 is based on template engine 3.1, that's why it doesn't work. This feature will be available in Visual Studio 17, as in this version newer version template engine 6.0.1xx will be used.

Closing as not a bug, please let me know if you need more info.

**Closed by vlada-shubina** 2021-07-23 18:55 UTC

**Comment by sayedihashimi** [comment] 2021-07-23 20:36
VS 17 means VS2022.

**Comment by McMlok** [comment] 2021-07-24 04:49
OK, thank you for clarification. I will wait until VS2022 release until CLI must be enough.
