### ISSUE TITLE
No error and status output when trying to install template pack from private NuGet feed

### ISSUE THREAD

**Issue by Sam13** [dotnet/templating#3967] opened 2021-09-30 15:21 UTC
I have a template pack in a private NuGet feed.
I tried to install the template pack with various installation command lines but never got any output or error message.
The command completes by listing the templates already installed. This does not include the ones from my template pack.
I tried those command lines:
````dotnet new -i MyTemplatePack````
````dotnet new -i MyTemplatePack --nuget-source https://mynugetserver.ext/feedurl````
````dotnet new -i MyTemplatePack --nuget-source https://mynugetserver.ext/feedurl --interactive````

When I download the package manually and install it from the local filesystem it works.
```dotnet new -i MyTemplatePack.nupkg``` 

````
dotnet --version
5.0.401
````

How can I diagnose that further? I assume something with NuGet download goes wrong but cannot find any log or status output...

**Comment by prashanth-nagaraj** [comment] 2021-10-03 19:27
I have the same issue. 

I have successfully pushed a template pack to Github Packages (Enterprise). When I try to install the package with the following command, the command succeeds with out any error message. But the template is not installed.

Commands tried:
`dotnet new -i my-nuget-package --nuget-source "https://nuget.pkg.github.com/my-org/index.json"`
`dotnet new -i my-nuget-package --nuget-source "https://nuget.pkg.github.com/my-org/index.json" --interactive`

And I'm able to install the pack successfully in the following scenarios.

- Download the package from Github Packages and install using the following command.
`dotnet new -i my-nuget-package.nupkg`

- Install from the package created locally from source code before pushing it to Github Packages.
`dotnet pack --configuration Release`
`dotnet new -i .\bin\Release\my-nuget-package.nupkg`

```
dotnet --version
5.0.401
```

**Comment by vlada-shubina** [comment] 2021-10-04 11:06
Duplicate of https://github.com/dotnet/templating/issues/3931.
It is fixed in next release, you may want to try to upgrade to .NET 6 rc1 version if possible.

**Closed by vlada-shubina** 2021-10-04 11:06 UTC
