### ISSUE TITLE
With .Net5 Preview7 installed, All texts in CLI are unlocalized for SC.

### ISSUE THREAD

**Issue by vdanche** [dotnet/templating#2420] opened 2020-07-22 08:57 UTC
**Repro Steps:**
Install .net5 preview7 SDK(5.0.100-preview.7.20366.15) on Chinese OS.
Run dotnet command(e.g dotnet --info / dotnet new console /dotnet build /dotnet --help...) in CLI

**Expected Result:**
The texts should be localized well.
**Actual Result:**
All texts are unlocalized, show as EN
![image](https://user-images.githubusercontent.com/65637796/88156543-27705a00-cc3c-11ea-8fa9-11fde2d82ca8.png)
![image](https://user-images.githubusercontent.com/65637796/88156707-60a8ca00-cc3c-11ea-9e5e-d64032f68635.png)

**Comment by ladipro** [comment] 2020-07-22 14:10
@vdanche is this the same issue as https://github.com/dotnet/templating/issues/2385 or are you seeing something else in Preview7 compared to Preview5? Thanks!

**Comment by grinrag** [comment] 2020-07-28 14:06
I am closing this issue as a duplicate of #2385, since there were no changes regarding localization fix.

**Closed by grinrag** 2020-07-28 14:06 UTC
