### ISSUE TITLE
No template is installed when running `dotnet new --install`

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/templating#3752] opened 2021-08-11 15:04 UTC
I tried to install the UNO project template using `dotnet new -i Uno.ProjectTemplates.Dotnet` but nothing is installed.
The Output:
```
Vorlagenname                                  Kurzname             Sprache     Tags
--------------------------------------------  -------------------  ----------  ----------------------
Console Application                           console              [C#],F#,VB  Common/Console
Class library                                 classlib             [C#],F#,VB  Common/Library
WPF Application                               wpf                  [C#],VB     Common/WPF
WPF Class library                             wpflib               [C#],VB     Common/WPF
WPF Custom Control Library                    wpfcustomcontrollib  [C#],VB     Common/WPF
WPF User Control Library                      wpfusercontrollib    [C#],VB     Common/WPF
Windows Forms App                             winforms             [C#],VB     Common/WinForms
Windows Forms Control Library                 winformscontrollib   [C#],VB     Common/WinForms
Windows Forms Class Library                   winformslib          [C#],VB     Common/WinForms
Worker Service                                worker               [C#],F#     Common/Worker/Web
MSTest Test Project                           mstest               [C#],F#,VB  Test/MSTest
NUnit 3 Test Project                          nunit                [C#],F#,VB  Test/NUnit
NUnit 3 Test Item                             nunit-test           [C#],F#,VB  Test/NUnit
xUnit Test Project                            xunit                [C#],F#,VB  Test/xUnit
Razor Component                               razorcomponent       [C#]        Web/ASP.NET
Razor Page                                    page                 [C#]        Web/ASP.NET
MVC ViewImports                               viewimports          [C#]        Web/ASP.NET
MVC ViewStart                                 viewstart            [C#]        Web/ASP.NET
Blazor Server App                             blazorserver         [C#]        Web/Blazor
Blazor WebAssembly App                        blazorwasm           [C#]        Web/Blazor/WebAssembly
ASP.NET Core Empty                            web                  [C#],F#     Web/Empty
ASP.NET Core Web App (Model-View-Controller)  mvc                  [C#],F#     Web/MVC
ASP.NET Core Web App                          webapp               [C#]        Web/MVC/Razor Pages
ASP.NET Core with Angular                     angular              [C#]        Web/MVC/SPA
ASP.NET Core with React.js                    react                [C#]        Web/MVC/SPA
ASP.NET Core with React.js and Redux          reactredux           [C#]        Web/MVC/SPA
Razor Class Library                           razorclasslib        [C#]        Web/Razor/Library
ASP.NET Core Web API                          webapi               [C#],F#     Web/WebAPI
ASP.NET Core gRPC Service                     grpc                 [C#]        Web/gRPC
dotnet gitignore file                         gitignore                        Config
global.json file                              globaljson                       Config
NuGet Config                                  nugetconfig                      Config
Dotnet local tool manifest file               tool-manifest                    Config
Web Config                                    webconfig                        Config
Solution File                                 sln                              Solution
Protocol Buffer File                          proto                            Web/gRPC

Examples:
    dotnet new mvc --auth Individual
    dotnet new blazorwasm
    dotnet new --help
    dotnet new nunit --help
```

I also tried `dotnet new -i Microsoft.DotNet.Web.Spa.ProjectTemplates` as shown in the [docs](https://docs.microsoft.com/en-us/dotnet/core/install/templates?pivots=os-windows) but this also did not work.

`dotnet --version` shows `5.0.301`

I'm not sure if that is related but I also installed `3.1.4.12` today. But I can't say if it worked before.

**Comment by vlada-shubina** [comment] 2021-08-30 08:52
@LokiMidgard 
Likely in case above the installation failed, however `dotnet new` has poor logging for install in 5.0, so the error is not shown.

We improved the install UX in .NET 6 (preview 4), if it works for you could you please install the latest .NET 6 preview and try again?

As for troubleshooting for 5.0.301, I may suggest to start with trying to perform `dotnet restore` manually as described [here](https://github.com/dotnet/templating/issues/2763#issuecomment-763711737) and see if it works. 

If you can afford losing all previously installed templates for dotnet new, removing `C:\Users\<username>\.templateengine\dotnetcli\5.0.301 folder content may also help (if settings got corrupted) but it will remove all previously installed templates.

**Comment by LokiMidgard** [comment] 2021-08-30 11:04
@vlada-shubina

I have already installed .net 6 preview `6.0.100-preview.7.21379.14`. I tried to install the template again and it worked now...

I don't know how to use the .net 5 version to install the template and I would prefre to not delete it, so I can't give you better information over error.

**Comment by vlada-shubina** [comment] 2021-08-31 09:57
@LokiMidgard you can use [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) to specify SDK version to use.
As the problem is solved, I'm closing the issue, please let me know in case of any further problems.

**Closed by vlada-shubina** 2021-08-31 09:57 UTC
Labels: need-customer-info
