### ISSUE TITLE
Solution isn't updated when excluding project with modifier

### ISSUE THREAD

**Issue by pierceboggan** [dotnet/templating#966] opened 2017-06-19 16:25 UTC
# Steps to Reproduce

1. Create a `.template.config` for a solution with multiple projects. 
2. Add a symbol/modifier to remove one of these projects.
3. `dotnet new`, and ensure that the symbol for removing the project is set to `true`.

# Expected Behavior

Because I am excluding an entire directory with a csproj, I expect the folder containing this project to not unfold, and that the solution is updated to remove this project.

# Actual Behavior

The folder containing the excluded csproj is not unfolded (as expected), but the solution is not updated to reflect this.

**Comment by pierceboggan** [comment] 2017-06-19 16:35
Seems like it would just need to strip it out:

```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "BlankApp.Android", "Droid\BlankApp.Android.csproj", "{059A7B4B-29F5-47C3-8A44-6A620AEEA28D}"
EndProject
```

Anything with the path I've excluded should be stripped (in this case, my modifier removed the `Droid` directory).

**Comment by sayedihashimi** [comment] 2017-06-19 17:57
I think you'd need to exclude that in the .sln file via optional content, but let's see if @mlorbetske has some better ideas.

**Comment by mlorbetske** [comment] 2017-06-19 18:42
Yep, that'd be the approach - to add conditioning to the solution file that keys on the same symbol that's used in the modifier

**Comment by seancpeters** [comment] 2017-06-19 20:25
For conditionally including / excluding content from a .sln file, the syntax for the conditional statements is:
```
//#if (<condition>)
//#elseif (<condition>)
//#else
//#endif
```
...and the corresponding `////` versions for conditional uncommenting in conjunction to including or excluding the content.

I created a small solution template with 2 projects in it, and added conditioning based on a boolean parameter called "useOther". I believe this example will satisfy your needs, @pierceboggan :
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26613.0
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Company.ClassLibrary1", "MultiProjectTest\Company.ClassLibrary1.csproj", "{8FD9C741-9EC7-4D23-AE19-8AAFA34F9402}"
EndProject
//#if (useOther)
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "OtherProject", "OtherProject\OtherProject.csproj", "{6131A358-96A3-48CF-9DA0-5C1A6EB67BEA}"
EndProject
//#endif
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8FD9C741-9EC7-4D23-AE19-8AAFA34F9402}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{8FD9C741-9EC7-4D23-AE19-8AAFA34F9402}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{8FD9C741-9EC7-4D23-AE19-8AAFA34F9402}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{8FD9C741-9EC7-4D23-AE19-8AAFA34F9402}.Release|Any CPU.Build.0 = Release|Any CPU
//#if (useOther)
		{6131A358-96A3-48CF-9DA0-5C1A6EB67BEA}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{6131A358-96A3-48CF-9DA0-5C1A6EB67BEA}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{6131A358-96A3-48CF-9DA0-5C1A6EB67BEA}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{6131A358-96A3-48CF-9DA0-5C1A6EB67BEA}.Release|Any CPU.Build.0 = Release|Any CPU
//#endif
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {09C5699D-670E-48BB-9CCE-5A20A387CC9B}
	EndGlobalSection
EndGlobal
```
With this setup, if my useOther symbol is set to false, the "OtherProject" statements are excluded from the .sln file.

If you use the same condition(s) in the .sln files as in the sources section of the template.json, the output should be as expected. 

Please let me know if you run into any issues using this approach, and we can work through them together to get the results you expect.

**Comment by pierceboggan** [comment] 2017-06-19 23:23
@seancpeters This worked great! Perhaps we should ensure there is a sample for this / this is documented over at [dotnet-template-samples](https://github.com/dotnet/dotnet-template-samples).

**Comment by seancpeters** [comment] 2017-06-19 23:27
Good to hear! I think this was the first I've heard of conditioning a solution file - agree it should get documented. @sayedihashimi - can you coordinate the documentation? (I can provide examples as needed)

**Comment by sayedihashimi** [comment] 2017-06-20 02:27
Yes we should add a sample for this. I've created https://github.com/dotnet/dotnet-template-samples/issues/17 to track it. 

I think everything is this issue has now been addressed.

**Comment by mlorbetske** [comment] 2017-06-27 18:09
@seancpeters this was addressed in #979 right?

**Comment by seancpeters** [comment] 2017-06-27 18:20
Between #979 and some workaround, I'd say this is taken care of.

**Comment by mlorbetske** [comment] 2017-06-28 02:24
Cool, closing for now, please re-open if needed

**Comment by egarim** [comment] 2021-08-07 12:17
Is it possible to use more complex conditions in order to exclude projects from the solution ? here is an example of what i need to do
these are my modifiers in template.json file 

"sources": 
  [
    {
      "modifiers": [
        {
          "condition": "(!android) && (!xamarinall)",
          "exclude": [ "MyApp.Mobile.Android/**/*" ]
        }
      ]
    }
  ]

and this is one of the conditions im using in my sln file

//#if ((!android) && (!xamarinall))
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyApp.Mobile.Android", "LobApp.Mobile.Android\LobApp.Mobile.Android.csproj", "{F3169BB6-77AE-4D8A-9854-2ECCCF73B7A6}"
EndProject
//#endif

Currently, the conditions are not working at the solution level? any idea in what I'm doing wrong?

**Comment by vlada-shubina** [comment] 2021-08-16 10:50
@egarim could you please open the new issue on this and attach the whole template so we can check? 
We were not able to reproduce the issue with example above.

**Closed by vlada-shubina** 2021-08-16 10:50 UTC
Labels: need-investigation
