### ISSUE TITLE
Provide better/more specific examples of SpecialCustomOperations usage

### ISSUE THREAD

**Issue by tillig** [dotnet/templating#2090] opened 2019-09-03 19:24 UTC
I'm working on a project that I want as a "runnable template" for an ASP.NET Core web project, but I found that the JSON syntax for replacement doesn't always yield something usable by Visual Studio. For example, in `launchSettings.json` if you have something like this...

```json
    "iisExpress": {
      "applicationUrl": "http://localhost:8080",
      //#if(!NoHttps)
      "sslPort": 44300
      //#else
      "sslPort": 0
      //#endif
    }
```

...then VS sees it as invalid JSON and the template isn't runnable anymore. It took several hours of guesswork and trial/error to determine that I could add a `SpecialCustomOperations` section like this...

```json
  "specialCustomOperations": {
    "**/*.json": {
      "operations": [
        {
          "configuration": {
            "actionableElse": [
              "//#else"
            ],
            "actionableElseif": [
              "//#elif"
            ],
            "actionableIf": [
              "//#if"
            ],
            "actions": [
              "pseudoComment"
            ],
            "endif": [
              "//#endif"
            ],
            "trim": "true",
            "wholeLine": "true"
          },
          "type": "conditional"
        },
        {
          "configuration": {
            "id": "pseudoComment",
            "original": "///",
            "replacement": ""
          },
          "type": "replacement"
        }
      ]
    }
  }
```

and it would allow me to use a triple-slash to provide something that would allow the project to be runnable again:

```json
    "iisExpress": {
      "applicationUrl": "http://localhost:8080",
      //#if(!NoHttps)
      "sslPort": 44300
      //#else
      ///"sslPort": 0
      //#endif
    }
```

There were a couple of challenges:

- It wasn't clear that you couldn't just add a `replacement` operation - you must have a `conditional` that executes the replacement action you define.
- I wasn't able to use a C-style comment replacement operation, like I had to use triple-slash `///` as the `original` in my replacement operation instead of just replacing double-slash `//`. I am _guessing_ this has to do with the tokenization of the statement being replaced and the order of operations or something. If I have `//` as the replacement, my custom op doesn't run. Triple-slash, it does.
- I don't know what the default configuration for JSON files is. Seeing that might have helped me copy/paste/modify my way to getting this done, but I couldn't find it.

Anyway, putting this all together would have been much easier with a bit more in the way of examples on the [wiki page about runnable templates](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) or possibly some pointers as to the default configuration.

**Comment by donJoseLuis** [comment] 2020-03-20 08:17
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Comment by donJoseLuis** [comment] 2020-03-24 12:35
"It took several hours of guesswork" that's not the UX we want in templating!
Let's update documentation.

**Comment by RehanSaeed** [comment] 2020-06-16 15:34
@tillig Here is an easier way that I've been using without any custom configuration:

```
      //#if (HttpsEverywhere)
      "sslPort": 44300
      ////#else
      //"sslPort": 0
      //#endif
```

The double comment in the `else` tells it to uncomment the block.

**Comment by bozturkMSFT** [comment] 2021-05-12 11:36
Closing this as a duplicate of #2516. Please let us know if you think otherwise.

**Closed by bozturkMSFT** 2021-05-12 11:36 UTC
Labels: size:1.0, triaged
