### ISSUE TITLE
Visual Studio 2019 creates invalid assembly name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/templating#2709] opened 2020-09-25 22:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1165370/visual-studio-2019-creates-invalid-assembly-name.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I tried to create a ASP.NET Core 3.1 Web App using the following project/solution name: "Can'tDebugFF".

Visual Studio apparently doesn't escape the project's assembly name.

The linker, too, doesn't complain about the illegal assembly name.

Debugging the web app then results in:

```
FileLoadException: The given assembly name or codebase was invalid. (0x80131047)

System.Reflection.AssemblyName.nInit()
```

Please fix by correctly escaping assembly name on project creation.

---
#### Feedback Bot on 8/27/2020, 08:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Pilchie** [comment] 2020-12-15 19:27
Moving to templating, because that's where this sort of escaping usually gets handled.

**Comment by vlada-shubina** [comment] 2020-12-21 17:21
@Pilchie  is this issue still reproducible? 

I cannot reproduce it any longer, tried both 5.0 and 3.1 SDK and 5.0 and 3.1 asp.net core template.  
I was able to repro it back in September though, I might connect it to new VS version or any SDK security patch.

**Comment by Pilchie** [comment] 2021-01-01 23:02
I'm not sure, I just moved the developer community issue.  I suggest following up there.

**Comment by vlada-shubina** [comment] 2021-01-18 12:24
The issue in developer community is already closed, and leads to this item. As we cannot reproduce it now, decision is to close it. 
Please don't hesitate to reopen if needed.

**Closed by vlada-shubina** 2021-01-18 12:24 UTC
