### ISSUE TITLE
dotnet new returns 0 exit code when it doesn't find template

### ISSUE THREAD

**Issue by nguerrera** [dotnet/templating#1971] opened 2019-06-29 15:12 UTC
When a template is not found, it prints a list of possible templates from the web, after a red error, but the return value is 0. I think the return value should still be non-zero in any case where we failed to actually instantiate a template.

```
> dotnet.exe new c
Couldn't find an installed template that matches the input, searching online for one that does...
Matches from template source: NuGet
-----------------------------------
Template name "Minimal microservice" (mcrsvc) from author "Peter Kottas" in pack PeterKottas.DotNetCore.WindowsService.Template
    To use this template, run the following command and try again:
        dotnet new -i PeterKottas.DotNetCore.WindowsService.Template::1.0.1

Template name "SAFE-Stack Web App v1.9.0" (SAFE) from author "Tomasz Heimowski" in pack SAFE.Template
    To use this template, run the following command and try again:
        dotnet new -i SAFE.Template::1.9.0

Template name "Fable.Template.Electron App" (fable-electron) from author "Andrew Olney" in pack Fable.Template.Electron
    To use this template, run the following command and try again:
        dotnet new -i Fable.Template.Electron::1.0.3

Template name "Expecto .net core Template" (expecto) from author "Michal Niegrzybowski" in pack Expecto.Template
    To use this template, run the following command and try again:
        dotnet new -i Expecto.Template::10.0.0

<snip>

> echo %ERRORLEVEL%
0
```

**Comment by donJoseLuis** [comment] 2020-03-20 07:07
this makes sense.
1. Adding item to specific project corresponding to a targeted delivery area
1. Once this has been done for the entire backlog, the next steps will be to prioritize within each project & output a delivery roadmap.
1. At that point, the issues will be assigned to a corresponding milestone
1. The team will then begin to deliver against the road map, contributions always welcome

**Closed** 2021-01-21 10:26 UTC
Labels: size:1.5, triaged

**Comment by vlada-shubina** [comment] 2021-01-21 10:28
The issue is fixed in scope of error handling improvements done in #2713 - now the error exit code will be returned in case template to run cannot be found.
