### ISSUE TITLE
Template not renaming "sourceName" folder on Ubuntu 14.94 LTS

### ISSUE THREAD

**Issue by dburriss** [dotnet/templating#1381] opened 2017-12-26 15:14 UTC
**Observed**
When templating a project that requires a folder to be renamed it works on Windows but not on Ubuntu.

**To Reproduce**
```
dotnet new -i "giraffe-template::*"
```
Create a new directory and run
`dotnet new giraffe`

On Windows it will be `src/<containing folder name>` but on Ubuntu it will be `src/<AppNamePlaceholder>`
**Environment**
OS: Ubuntu 14.04 LTS
Dotnet: 2.0.2

This may be as simple as a permission issue.

**Comment by donJoseLuis** [comment] 2020-03-19 18:04
let's look at this in the improved dotnet new ux road map bucket

**Comment by bekir-ozturk** [comment] 2021-06-01 09:39
Internal note: we will need to reproduce this first as it is likely fixed since the issue was opened.

**Comment by vlada-shubina** [comment] 2022-07-14 09:42
Closing, as it is related to not supported version of .NET. We are not aware of such issues for 3.1, 6.0 or 7.0. 
Please feel free to comment if you still experience this issue.

**Closed by vlada-shubina** 2022-07-14 09:42 UTC
Labels: triaged, size:1.0
