### ISSUE TITLE
files containing - gets translated incorrectly in files

### ISSUE THREAD

**Issue by hersing** [dotnet/templating#1744] opened 2019-01-22 13:45 UTC
When a file name contains "-" and is refereed in another file, the templates are replacing "-" with "_"

I have a .csproj file called "fiks-hej", and in the .sln file it is refereed to as:

`"fiks_hej", "fiks_hej\fiks_hej.csproj",`

**Comment by mlorbetske** [comment] 2019-01-23 21:37
Could you post the output of `dotnet new --debug:version` as well as the contents of your template.json please?

**Comment by donJoseLuis** [comment] 2020-03-19 21:24
hello @hersing could you please share your template JSon?

**Comment by donJoseLuis** [comment] 2020-03-20 05:11
this repro attempt should be easy to do.  In the case we cannot reproduce & no repro artifacts are provided we'll close the issue.

**Comment by grinrag** [comment] 2020-04-22 12:12
@hersing since the requested info was not provided, I am closing this issue. Feel free to open if the issue is still relevant for you.

**Closed by grinrag** 2020-04-22 12:12 UTC
Labels: need-customer-info, size:2.0, triaged
